<?php

declare(strict_types=1);

namespace FastWebsite\Services;

use FastWebsite\Core\HttpException;
use FastWebsite\Repositories\ProjectRepository;
use Throwable;

final class ProjectService
{
    private const TRANSITIONS=['submitted'=>['draft','under_review'],'changes_requested'=>['under_review','draft'],'approved'=>['under_review','approved'],'published'=>['approved','published'],'archived'=>['published','archived'],'restored'=>['archived','draft']];
    private const ROLES=['principal_investigator','co_investigator','project_manager','researcher','technical_staff','student','advisor','collaborator','other'];
    public function __construct(private readonly ProjectRepository$projects,private readonly AuthorizationService$authorization,private readonly AuditService$audit){}
    /** @param array<string,mixed> $data */ public function create(array$data,?int$unitId,int$userId,string$ip,string$agent):int{$this->requireDepartment($userId,'research.create',(int)$data['lead_department_id']);$this->requireUnitAccess($userId,$unitId);return$this->transaction(function()use($data,$unitId,$userId,$ip,$agent){$id=$this->projects->create($data);$this->projects->replaceLeadUnit($id,$unitId);$this->projects->recordRevision($id,null,[...$data,'lead_research_unit_id'=>$unitId],$userId,'Initial research project record');$this->audit->record($userId,'project.created','project',$id,$ip,$agent,['status'=>'draft']);return$id;});}
    /** @param array<string,mixed> $data */ public function createAndPublish(array$data,?int$unitId,int$userId,string$ip,string$agent):int{return$this->transaction(function()use($data,$unitId,$userId,$ip,$agent){if(!$this->canDirectPublish($userId,null,(int)$data['lead_department_id']))throw new HttpException(403,'You do not have all permissions required to publish this project.');$id=$this->create($data,$unitId,$userId,$ip,$agent);$this->publishDraft($id,$userId,'Created and published directly.',$ip,$agent);return$id;});}
    /** @param array<string,mixed> $data */ public function update(int$id,array$data,?int$unitId,int$userId,string$note,string$ip,string$agent):void{$this->requireProject($userId,'research.edit',$id);$this->requireDepartment($userId,'research.edit',(int)$data['lead_department_id']);$this->requireUnitAccess($userId,$unitId);$this->transaction(function()use($id,$data,$unitId,$userId,$note,$ip,$agent){$previous=$this->projects->findForUpdate($id);if($previous===null)throw new HttpException(404,'Project not found.');if($previous['publication_status']!=='draft')throw new HttpException(409,'Only draft projects can be edited.');$this->saveRevision($id,$data,$unitId,$previous,$userId,$note,$ip,$agent,'project.updated');});}
    /** @param array<string,mixed> $data */ public function updatePublished(int$id,array$data,?int$unitId,int$userId,string$note,string$ip,string$agent):void{if(!$this->canDirectPublish($userId,$id,(int)$data['lead_department_id']))throw new HttpException(403,'Editing a published project requires publishing access.');$this->requireUnitAccess($userId,$unitId);$this->transaction(function()use($id,$data,$unitId,$userId,$note,$ip,$agent){$previous=$this->projects->findForUpdate($id);if($previous===null)throw new HttpException(404,'Project not found.');if($previous['publication_status']!=='published')throw new HttpException(409,'The project is no longer published. Reload before editing.');$this->requireSummary($data);$this->saveRevision($id,$data,$unitId,$previous,$userId,$note!==''?$note:'Published project updated',$ip,$agent,'project.published_updated');});}
    /** @param array<string,mixed> $data */ public function updateAndPublish(int$id,array$data,?int$unitId,int$userId,string$note,string$ip,string$agent):void{$this->transaction(function()use($id,$data,$unitId,$userId,$note,$ip,$agent){$this->update($id,$data,$unitId,$userId,$note,$ip,$agent);$this->publishDraft($id,$userId,'Direct publication.',$ip,$agent);});}
    public function publishDraft(int$id,int$userId,string$comment,string$ip,string$agent):void{$this->transaction(function()use($id,$userId,$comment,$ip,$agent){if(!$this->canDirectPublish($userId,$id))throw new HttpException(403,'You do not have all permissions required to publish this project.');foreach(['submitted','approved','published']as$action)$this->transition($id,$action,$userId,$comment,$ip,$agent);});}
    public function transition(int$id,string$action,int$userId,string$comment,string$ip,string$agent):string{return$this->transaction(function()use($id,$action,$userId,$comment,$ip,$agent){$project=$this->projects->findForUpdate($id);if($project===null)throw new HttpException(404,'Project not found.');if(!isset(self::TRANSITIONS[$action]))throw new HttpException(403,'That project workflow action is unavailable.');if($action==='changes_requested'&&trim($comment)==='')throw new HttpException(409,'A comment is required when requesting changes.');[$from,$target]=self::TRANSITIONS[$action];if($project['publication_status']!==$from)throw new HttpException(409,'The project publication status has changed.');$permission=match($action){'submitted'=>'research.edit','approved','changes_requested'=>'content.approve',default=>'research.publish'};$this->requireProject($userId,$permission,$id);if(in_array($target,['under_review','published'],true))$this->requireSummary($project);$this->projects->changeStatus($id,$target);$this->projects->recordApproval($id,$action,$userId,$comment);$this->audit->record($userId,'project.'.$action,'project',$id,$ip,$agent,['from_status'=>$from,'to_status'=>$target]);return$target;});}
    public function addMember(int$projectId,?int$staffId,string$externalName,string$affiliation,string$email,string$role,string$title,string$start,string$end,int$order,int$userId,string$ip,string$agent):void{$this->requireProject($userId,'research.edit',$projectId);$externalName=trim($externalName);if(($staffId===null&&$externalName==='')||($staffId!==null&&$externalName!==''))throw new HttpException(409,'Choose one internal staff member or enter one external member name.');if($staffId!==null&&(!$this->projects->relationExists('staff',$staffId)||!$this->projects->canUseStaff($userId,$staffId)))throw new HttpException(409,'Choose a valid staff member within your access.');if(!in_array($role,self::ROLES,true))throw new HttpException(409,'Choose a valid project role.');$start=$this->date($start,'Start date');$end=$this->date($end,'End date');if($start!==null&&$end!==null&&$end<$start)throw new HttpException(409,'End date cannot be before the start date.');$email=trim($email);if($email!==''&&filter_var($email,FILTER_VALIDATE_EMAIL)===false)throw new HttpException(409,'Enter a valid external member email.');$this->transaction(function()use($projectId,$staffId,$externalName,$affiliation,$email,$role,$title,$start,$end,$order,$userId,$ip,$agent){$id=$this->projects->addMember($projectId,$staffId,$externalName!==''?mb_substr($externalName,0,200):null,trim($affiliation)!==''?mb_substr(trim($affiliation),0,255):null,$email!==''?mb_substr($email,0,190):null,$role,trim($title)!==''?mb_substr(trim($title),0,150):null,$start,$end,max(0,min(65535,$order)));$this->audit->record($userId,'project.member_added','project',$projectId,$ip,$agent,['member_id'=>$id,'staff_id'=>$staffId,'external'=>$externalName!==''?'yes':'no','role'=>$role]);});}
    public function removeMember(int$projectId,int$memberId,int$userId,string$ip,string$agent):void{$this->requireProject($userId,'research.edit',$projectId);$this->transaction(function()use($projectId,$memberId,$userId,$ip,$agent){if(!$this->projects->removeMember($projectId,$memberId))throw new HttpException(404,'Project member not found.');$this->audit->record($userId,'project.member_removed','project',$projectId,$ip,$agent,['member_id'=>$memberId]);});}
    /** @return list<array{action:string,label:string}> */ public function actions(int$userId,int$id,string$status):array{if(!$this->projects->canAccess($userId,$id))return[];$definitions=['submitted'=>['draft','research.edit','Submit for review'],'changes_requested'=>['under_review','content.approve','Request changes'],'approved'=>['under_review','content.approve','Approve'],'published'=>['approved','research.publish','Publish'],'archived'=>['published','research.publish','Archive'],'restored'=>['archived','research.publish','Restore as draft']];$result=[];foreach($definitions as$action=>[$from,$permission,$label])if($status===$from&&$this->authorization->can($userId,$permission))$result[]=['action'=>$action,'label'=>$label];return$result;}
    public function canDirectPublish(int$userId,?int$id=null,?int$departmentId=null):bool{$scope=$id!==null?$this->projects->canAccess($userId,$id):($departmentId!==null&&$this->projects->canUseDepartment($userId,$departmentId));return$scope&&$this->authorization->can($userId,'research.edit')&&$this->authorization->can($userId,'research.publish')&&$this->authorization->can($userId,'content.approve');}
    public function canCreate(int$userId):bool{return$this->authorization->can($userId,'research.create')&&$this->projects->departments($userId)!==[];}
    /** @param array<string,mixed> $data @param array<string,mixed> $previous */ private function saveRevision(int$id,array$data,?int$unitId,array$previous,int$userId,string$note,string$ip,string$agent,string$action):void{$this->projects->update($id,$data);$this->projects->replaceLeadUnit($id,$unitId);$this->projects->recordRevision($id,$previous,[...$data,'lead_research_unit_id'=>$unitId,'publication_status'=>$previous['publication_status']],$userId,$note!==''?$note:'Project updated');$this->audit->record($userId,$action,'project',$id,$ip,$agent,['publication_status'=>$previous['publication_status']]);}
    /** @param array<string,mixed> $data */ private function requireSummary(array$data):void{if(trim((string)($data['summary']??''))==='')throw new HttpException(409,'Add a project summary before publishing.');}private function requireProject(int$userId,string$permission,int$id):void{if(!$this->authorization->can($userId,$permission)||!$this->projects->canAccess($userId,$id))throw new HttpException(403,'This project action is outside your access.');}private function requireDepartment(int$userId,string$permission,int$id):void{if(!$this->authorization->can($userId,$permission)||!$this->projects->canUseDepartment($userId,$id))throw new HttpException(403,'This department is outside your project access.');}private function requireUnitAccess(int$userId,?int$id):void{if(!$this->projects->canUseUnit($userId,$id))throw new HttpException(403,'This research unit is outside your access.');}
    private function date(string$value,string$label):?string{$value=trim($value);if($value==='')return null;if(preg_match('/^\d{4}-\d{2}-\d{2}$/',$value)!==1||strtotime($value)===false)throw new HttpException(409,$label.' must use YYYY-MM-DD.');return$value;}
    private function transaction(callable$operation):mixed{$connection=$this->projects->connection();$owns=!$connection->inTransaction();if($owns)$connection->beginTransaction();try{$result=$operation();if($owns)$connection->commit();return$result;}catch(Throwable$e){if($owns&&$connection->inTransaction())$connection->rollBack();throw$e;}}
}
