<?php

declare(strict_types=1);

namespace FastWebsite\Services;

use FastWebsite\Core\HttpException;use FastWebsite\Repositories\PublicationRepository;use Throwable;

final class PublicationService
{
    private const TRANSITIONS=['submitted'=>['draft','under_review'],'changes_requested'=>['under_review','draft'],'approved'=>['under_review','approved'],'published'=>['approved','published'],'archived'=>['published','archived'],'restored'=>['archived','draft']];
    public function __construct(private readonly PublicationRepository$publications,private readonly AuthorizationService$authorization,private readonly AuditService$audit){}
    /** @param array<string,mixed> $data */ public function create(array$data,?int$projectId,?int$unitId,int$userId,string$ip,string$agent):int{$this->requireCreateScope($userId,$projectId,$unitId);return$this->transaction(function()use($data,$projectId,$unitId,$userId,$ip,$agent){$id=$this->publications->create($data);$this->publications->replaceLinks($id,$projectId,$unitId);$this->publications->recordRevision($id,null,[...$data,'project_id'=>$projectId,'research_unit_id'=>$unitId],$userId,'Initial publication record');$this->audit->record($userId,'publication.created','publication',$id,$ip,$agent,['status'=>'draft']);return$id;});}
    /** @param array<string,mixed> $data */ public function update(int$id,array$data,?int$projectId,?int$unitId,int$userId,string$note,string$ip,string$agent):void{$this->requirePublication($userId,'research.edit',$id);$this->requireLinks($userId,$projectId,$unitId);$this->transaction(function()use($id,$data,$projectId,$unitId,$userId,$note,$ip,$agent){$previous=$this->publications->findForUpdate($id);if($previous===null)throw new HttpException(404,'Publication not found.');if($previous['status']!=='draft')throw new HttpException(409,'Only draft publications can be edited.');$this->saveRevision($id,$data,$projectId,$unitId,$previous,$userId,$note,$ip,$agent,'publication.updated');});}
    /** @param array<string,mixed> $data */ public function updatePublished(int$id,array$data,?int$projectId,?int$unitId,int$userId,string$note,string$ip,string$agent):void{if(!$this->canDirectPublish($userId,$id))throw new HttpException(403,'Editing a published publication requires publishing access.');$this->requireLinks($userId,$projectId,$unitId);$this->transaction(function()use($id,$data,$projectId,$unitId,$userId,$note,$ip,$agent){$previous=$this->publications->findForUpdate($id);if($previous===null)throw new HttpException(404,'Publication not found.');if($previous['status']!=='published')throw new HttpException(409,'The publication is no longer published. Reload before editing.');$this->saveRevision($id,$data,$projectId,$unitId,$previous,$userId,$note!==''?$note:'Published publication updated',$ip,$agent,'publication.published_updated');});}
    /** @param array<string,mixed> $data */ public function updateAndPublish(int$id,array$data,?int$projectId,?int$unitId,int$userId,string$note,string$ip,string$agent):void{$this->transaction(function()use($id,$data,$projectId,$unitId,$userId,$note,$ip,$agent){$this->update($id,$data,$projectId,$unitId,$userId,$note,$ip,$agent);$this->publishDraft($id,$userId,'Direct publication.',$ip,$agent);});}
    public function publishDraft(int$id,int$userId,string$comment,string$ip,string$agent):void{$this->transaction(function()use($id,$userId,$comment,$ip,$agent){if(!$this->canDirectPublish($userId,$id))throw new HttpException(403,'You do not have all permissions required to publish this publication.');if($this->publications->authors($id)===[])throw new HttpException(409,'Add at least one author before publishing.');foreach(['submitted','approved','published']as$action)$this->transition($id,$action,$userId,$comment,$ip,$agent);});}
    public function transition(int$id,string$action,int$userId,string$comment,string$ip,string$agent):string{return$this->transaction(function()use($id,$action,$userId,$comment,$ip,$agent){$publication=$this->publications->findForUpdate($id);if($publication===null)throw new HttpException(404,'Publication not found.');if(!isset(self::TRANSITIONS[$action]))throw new HttpException(403,'That publication workflow action is unavailable.');if($action==='changes_requested'&&trim($comment)==='')throw new HttpException(409,'A comment is required when requesting changes.');[$from,$target]=self::TRANSITIONS[$action];if($publication['status']!==$from)throw new HttpException(409,'The publication status has changed.');$permission=match($action){'submitted'=>'research.edit','approved','changes_requested'=>'content.approve',default=>'research.publish'};$this->requirePublication($userId,$permission,$id);if(in_array($target,['under_review','published'],true)&&$this->publications->authors($id)===[])throw new HttpException(409,'Add at least one author before review or publication.');$this->publications->changeStatus($id,$target);$this->publications->recordApproval($id,$action,$userId,$comment);$this->audit->record($userId,'publication.'.$action,'publication',$id,$ip,$agent,['from_status'=>$from,'to_status'=>$target]);return$target;});}
    public function addAuthor(int$id,?int$staffId,string$name,string$affiliation,string$orcid,int$order,bool$corresponding,int$userId,string$ip,string$agent):void{$this->requireMutable($id,$userId);$name=trim($name);if(($staffId===null&&$name==='')||($staffId!==null&&$name!==''))throw new HttpException(409,'Choose one internal staff author or enter one external author name.');if($staffId!==null&&(!$this->publications->relationExists('staff',$staffId)||!$this->publications->canUseStaff($userId,$staffId)))throw new HttpException(409,'Choose a valid staff author within your access.');$orcid=trim($orcid);if($orcid!==''&&preg_match('/^\d{4}-\d{4}-\d{4}-\d{3}[\dX]$/i',$orcid)!==1)throw new HttpException(409,'ORCID must use the format 0000-0000-0000-0000.');$this->transaction(function()use($id,$staffId,$name,$affiliation,$orcid,$order,$corresponding,$userId,$ip,$agent){$author=$this->publications->addAuthor($id,$staffId,$name!==''?mb_substr($name,0,200):null,trim($affiliation)!==''?mb_substr(trim($affiliation),0,255):null,$orcid!==''?strtoupper($orcid):null,max(1,min(65535,$order)),$corresponding);$this->audit->record($userId,'publication.author_added','publication',$id,$ip,$agent,['author_id'=>$author,'staff_id'=>$staffId,'order'=>max(1,$order)]);});}
    public function removeAuthor(int$id,int$authorId,int$userId,string$ip,string$agent):void{$this->requireMutable($id,$userId);$this->transaction(function()use($id,$authorId,$userId,$ip,$agent){if(!$this->publications->removeAuthor($id,$authorId))throw new HttpException(404,'Publication author not found.');$this->audit->record($userId,'publication.author_removed','publication',$id,$ip,$agent,['author_id'=>$authorId]);});}
    // --- Staff self-service: ownership (is this staff an author of this
    // publication), not RBAC permissions, gates these. The caller must have
    // already resolved $staffId for the logged-in user before calling. ---
    /** @param array<string,mixed> $data */ public function createOwn(array$data,?int$projectId,?int$unitId,int$staffId,int$userId,string$ip,string$agent):int{return$this->transaction(function()use($data,$projectId,$unitId,$staffId,$userId,$ip,$agent){$id=$this->publications->create($data);$this->publications->replaceLinks($id,$projectId,$unitId);$this->publications->recordRevision($id,null,[...$data,'project_id'=>$projectId,'research_unit_id'=>$unitId],$userId,'Initial publication record');$this->publications->addAuthor($id,$staffId,null,null,null,1,false);$this->audit->record($userId,'publication.created','publication',$id,$ip,$agent,['status'=>'draft']);return$id;});}
    /** @param array<string,mixed> $data */ public function updateOwn(int$id,array$data,?int$projectId,?int$unitId,int$staffId,int$userId,string$note,string$ip,string$agent):void{$this->requireOwnAuthor($id,$staffId);$this->transaction(function()use($id,$data,$projectId,$unitId,$userId,$note,$ip,$agent):void{$previous=$this->publications->findForUpdate($id);if($previous===null)throw new HttpException(404,'Publication not found.');$this->publications->update($id,$data);$this->publications->replaceLinks($id,$projectId,$unitId);$this->publications->recordRevision($id,$previous,[...$data,'project_id'=>$projectId,'research_unit_id'=>$unitId,'status'=>$previous['status']],$userId,$note!==''?$note:'Publication updated by staff member');$this->audit->record($userId,'publication.self_updated','publication',$id,$ip,$agent,['status'=>$previous['status']]);});}
    public function addOwnAuthor(int$id,int$staffId,?int$coAuthorStaffId,string$name,string$affiliation,string$orcid,int$order,bool$corresponding,int$userId,string$ip,string$agent):void{$this->requireOwnAuthor($id,$staffId);$name=trim($name);if(($coAuthorStaffId===null&&$name==='')||($coAuthorStaffId!==null&&$name!==''))throw new HttpException(409,'Choose one internal staff author or enter one external author name.');if($coAuthorStaffId!==null&&!$this->publications->relationExists('staff',$coAuthorStaffId))throw new HttpException(409,'Choose a valid staff author.');$orcid=trim($orcid);if($orcid!==''&&preg_match('/^\d{4}-\d{4}-\d{4}-\d{3}[\dX]$/i',$orcid)!==1)throw new HttpException(409,'ORCID must use the format 0000-0000-0000-0000.');$this->transaction(function()use($id,$coAuthorStaffId,$name,$affiliation,$orcid,$order,$corresponding,$userId,$ip,$agent){$author=$this->publications->addAuthor($id,$coAuthorStaffId,$name!==''?mb_substr($name,0,200):null,trim($affiliation)!==''?mb_substr(trim($affiliation),0,255):null,$orcid!==''?strtoupper($orcid):null,max(1,min(65535,$order)),$corresponding);$this->audit->record($userId,'publication.author_added','publication',$id,$ip,$agent,['author_id'=>$author,'staff_id'=>$coAuthorStaffId]);});}
    public function removeOwnAuthor(int$id,int$staffId,int$authorId,int$userId,string$ip,string$agent):void{$this->requireOwnAuthor($id,$staffId);$this->transaction(function()use($id,$authorId,$userId,$ip,$agent){if(!$this->publications->removeAuthor($id,$authorId))throw new HttpException(404,'Publication author not found.');$this->audit->record($userId,'publication.author_removed','publication',$id,$ip,$agent,['author_id'=>$authorId]);});}
    public function ownsPublication(int$id,int$staffId):bool{return in_array($staffId,array_column($this->publications->authors($id),'staff_id'),true);}
    private function requireOwnAuthor(int$id,int$staffId):void{if(!$this->ownsPublication($id,$staffId))throw new HttpException(404,'Publication not found.');}

    /** @return list<array{action:string,label:string}> */ public function actions(int$userId,int$id,string$status):array{if(!$this->publications->canAccess($userId,$id))return[];$defs=['submitted'=>['draft','research.edit','Submit for review'],'changes_requested'=>['under_review','content.approve','Request changes'],'approved'=>['under_review','content.approve','Approve'],'published'=>['approved','research.publish','Publish'],'archived'=>['published','research.publish','Archive'],'restored'=>['archived','research.publish','Restore as draft']];$result=[];foreach($defs as$action=>[$from,$permission,$label])if($status===$from&&$this->authorization->can($userId,$permission))$result[]=['action'=>$action,'label'=>$label];return$result;}
    public function canDirectPublish(int$userId,int$id):bool{return$this->publications->canAccess($userId,$id)&&$this->authorization->can($userId,'research.edit')&&$this->authorization->can($userId,'research.publish')&&$this->authorization->can($userId,'content.approve');}public function canCreate(int$userId):bool{return$this->authorization->can($userId,'research.create')&&($this->publications->hasGlobalScope($userId)||$this->publications->projects($userId)!==[]||$this->publications->researchUnits($userId)!==[]);}
    /** @param array<string,mixed> $data @param array<string,mixed> $previous */ private function saveRevision(int$id,array$data,?int$projectId,?int$unitId,array$previous,int$userId,string$note,string$ip,string$agent,string$action):void{$this->publications->update($id,$data);$this->publications->replaceLinks($id,$projectId,$unitId);$this->publications->recordRevision($id,$previous,[...$data,'project_id'=>$projectId,'research_unit_id'=>$unitId,'status'=>$previous['status']],$userId,$note!==''?$note:'Publication updated');$this->audit->record($userId,$action,'publication',$id,$ip,$agent,['status'=>$previous['status']]);}
    private function requireCreateScope(int$userId,?int$projectId,?int$unitId):void{if(!$this->authorization->can($userId,'research.create'))throw new HttpException(403,'This publication action is not allowed.');if(!$this->publications->hasGlobalScope($userId)&&$projectId===null&&$unitId===null)throw new HttpException(403,'Select a project or research unit within your scope.');$this->requireLinks($userId,$projectId,$unitId);}private function requireLinks(int$userId,?int$projectId,?int$unitId):void{if(!$this->publications->canUseProject($userId,$projectId)||!$this->publications->canUseUnit($userId,$unitId))throw new HttpException(403,'A linked research record is outside your access.');}private function requirePublication(int$userId,string$permission,int$id):void{if(!$this->authorization->can($userId,$permission)||!$this->publications->canAccess($userId,$id))throw new HttpException(403,'This publication action is outside your access.');}private function requireMutable(int$id,int$userId):void{$this->requirePublication($userId,'research.edit',$id);$publication=$this->publications->findForUpdate($id);if($publication===null)throw new HttpException(404,'Publication not found.');if($publication['status']==='published'&&!$this->canDirectPublish($userId,$id))throw new HttpException(403,'Changing authors on a published publication requires publishing access.');if(in_array($publication['status'],['under_review','approved','archived'],true))throw new HttpException(409,'Authors cannot be changed in the current publication state.');}
    private function transaction(callable$operation):mixed{$connection=$this->publications->connection();$owns=!$connection->inTransaction();if($owns)$connection->beginTransaction();try{$result=$operation();if($owns)$connection->commit();return$result;}catch(Throwable$e){if($owns&&$connection->inTransaction())$connection->rollBack();throw$e;}}
}
