<?php

declare(strict_types=1);

namespace FastWebsite\Validation;

use FastWebsite\Repositories\EngagementRepository;

final class EngagementValidator
{
    public function __construct(private readonly EngagementRepository$r){}
    /** @param array<string,mixed>$i @return array{data:array<string,mixed>,errors:list<string>} */public function partnership(array$i):array{$e=[];$partner=$this->id($i['partner_id']??null);$faculty=$this->id($i['faculty_id']??null);$doc=$this->id($i['document_id']??null);$title=mb_substr(trim((string)($i['title']??'')),0,255);$type=(string)($i['partnership_type']??'other');$start=$this->date($i['start_date']??null,'Start date',$e);$end=$this->date($i['end_date']??null,'End date',$e);if($title==='')$e[]='Partnership title is required.';if($partner===null||!$this->r->relation('partners',$partner))$e[]='Choose a published partner organization.';if($faculty===null||!$this->r->relation('faculties',$faculty))$e[]='Choose a valid faculty.';if(!in_array($type,['mou','research','teaching','student_exchange','staff_exchange','industry','community','funding','other'],true))$e[]='Choose a valid partnership type.';if($start&&$end&&$end<$start)$e[]='End date cannot precede start date.';if(trim((string)($i['document_id']??''))!==''&&($doc===null||!$this->r->relation('documents',$doc)))$e[]='Choose a valid document.';return['data'=>['partner_id'=>$partner,'faculty_id'=>$faculty,'title'=>$title,'partnership_type'=>$type,'description'=>$this->nullable($i['description']??null,100000),'start_date'=>$start,'end_date'=>$end,'reference_number'=>$this->nullable($i['reference_number']??null,120),'document_id'=>$doc],'errors'=>$e];}
    /** @param array<string,mixed>$i @return array{data:array<string,mixed>,errors:list<string>} */public function impact(array$i,int$u,?int$id=null):array{$e=[];$title=mb_substr(trim((string)($i['title']??'')),0,280);$slug=$this->slug((string)($i['slug']??''),$title);$dep=$this->id($i['department_id']??null);$project=$this->id($i['project_id']??null);$media=$this->id($i['featured_media_id']??null);if($title==='')$e[]='Impact story title is required.';if($slug===''||$this->r->impactSlugExists($slug,$id))$e[]=$slug===''?'A valid public URL is required.':'That impact story URL is already in use.';if(!$this->r->canUseDepartment($u,$dep))$e[]='Choose a department within your scope.';if(trim((string)($i['project_id']??''))!==''&&($project===null||!$this->r->relation('projects',$project)))$e[]='Choose a valid project.';if(trim((string)($i['featured_media_id']??''))!==''&&($media===null||!$this->r->relation('media',$media)))$e[]='Choose an active image.';$date=$this->date($i['impact_date']??null,'Impact date',$e);return['data'=>['department_id'=>$dep,'project_id'=>$project,'title'=>$title,'slug'=>$slug,'summary'=>$this->nullable($i['summary']??null,10000),'body'=>$this->nullable($i['body']??null,100000),'beneficiaries'=>$this->nullable($i['beneficiaries']??null,20000),'location_text'=>$this->nullable($i['location_text']??null,255),'impact_date'=>$date,'featured_media_id'=>$media],'errors'=>$e];}
    private function id(mixed$v):?int{$v=trim((string)$v);return ctype_digit($v)&&(int)$v>0?(int)$v:null;}private function nullable(mixed$v,int$m):?string{$v=mb_substr(trim((string)$v),0,$m);return$v===''?null:$v;}private function date(mixed$v,string$l,array&$e):?string{$v=trim((string)$v);if($v==='')return null;if(preg_match('/^\d{4}-\d{2}-\d{2}$/',$v)!==1||strtotime($v)===false){$e[]=$l.' must use YYYY-MM-DD.';return null;}return$v;}private function slug(string$v,string$f):string{$v=trim($v)!==''?$v:$f;$a=iconv('UTF-8','ASCII//TRANSLIT//IGNORE',$v);return trim(strtolower((string)preg_replace('/[^a-zA-Z0-9]+/','-',is_string($a)?$a:$v)),'-');}
}
