<?php

declare(strict_types=1);

namespace FastWebsite\Validation;

use FastWebsite\Repositories\InnovationRepository;

final class InnovationValidator
{
    public const TYPES=['prototype','patent','software','device','process','product','service','other'];
    public const STAGES=['concept','research','prototype','pilot','validated','commercialised','scaled','other'];
    public const FACILITY_TYPES=['laboratory','workshop','studio','computer_lab','testing_facility','field_site','office','other'];
    public const AVAILABILITY=['available','restricted','maintenance','unavailable','retired'];
    public function __construct(private readonly InnovationRepository$repository){}

    /** @param array<string,mixed>$input @return array{data:array<string,mixed>,errors:list<string>} */
    public function innovation(array$input,int$userId,?int$id=null):array{$errors=[];$name=mb_substr(trim((string)($input['name']??'')),0,255);$slug=$this->slug((string)($input['slug']??''),$name);$type=(string)($input['innovation_type']??'other');$stage=trim((string)($input['development_stage']??''));$department=$this->id($input['lead_department_id']??null);$project=$this->id($input['project_id']??null);$media=$this->id($input['hero_media_id']??null);if($name==='')$errors[]='Innovation name is required.';if($slug===''||$this->repository->innovationSlugExists($slug,$id))$errors[]=$slug===''?'A valid innovation URL is required.':'That innovation URL is already in use.';if(!in_array($type,self::TYPES,true))$errors[]='Choose a valid innovation type.';if($stage!==''&&!in_array($stage,self::STAGES,true))$errors[]='Choose a valid development stage.';if($department===null||!$this->repository->relationExists('departments',$department)||!$this->repository->canUseDepartment($userId,$department))$errors[]='Choose a lead department within your scope.';if(trim((string)($input['project_id']??''))!==''&&($project===null||!$this->repository->relationExists('projects',$project)))$errors[]='Choose a valid linked project.';if(trim((string)($input['hero_media_id']??''))!==''&&($media===null||!$this->repository->relationExists('media',$media)))$errors[]='Choose an active image.';$url=$this->nullable($input['external_url']??null,500);if($url!==null&&filter_var($url,FILTER_VALIDATE_URL)===false)$errors[]='Enter a complete external URL.';return['data'=>['project_id'=>$project,'lead_department_id'=>$department,'name'=>$name,'slug'=>$slug,'innovation_type'=>$type,'description'=>$this->nullable($input['description']??null,100000),'development_stage'=>$stage!==''?$stage:null,'intellectual_property_status'=>$this->nullable($input['intellectual_property_status']??null,200),'external_url'=>$url,'hero_media_id'=>$media],'errors'=>$errors];}

    /** @param array<string,mixed>$input @return array{data:array<string,mixed>,errors:list<string>} */
    public function facility(array$input,int$userId):array{$errors=[];$unit=$this->id($input['research_unit_id']??null);$location=$this->id($input['location_id']??null);$name=mb_substr(trim((string)($input['name']??'')),0,255);$type=(string)($input['facility_type']??'other');$status=(string)($input['status']??'active');if($name==='')$errors[]='Facility name is required.';if($unit===null||!$this->repository->relationExists('research_units',$unit)||!$this->repository->canUseUnit($userId,$unit))$errors[]='Choose a research unit within your scope.';if(!in_array($type,self::FACILITY_TYPES,true))$errors[]='Choose a valid facility type.';if(!in_array($status,['active','inactive','archived'],true))$errors[]='Choose a valid facility status.';if(trim((string)($input['location_id']??''))!==''&&($location===null||!$this->repository->relationExists('locations',$location)))$errors[]='Choose a valid location.';return['data'=>['research_unit_id'=>$unit,'name'=>$name,'facility_type'=>$type,'description'=>$this->nullable($input['description']??null,100000),'location_id'=>$location,'status'=>$status],'errors'=>$errors];}

    /** @param array<string,mixed>$input @return array{data:array<string,mixed>,errors:list<string>} */
    public function equipment(array$input,int$userId):array{$errors=[];$unit=$this->id($input['research_unit_id']??null);$facility=$this->id($input['facility_id']??null);$name=mb_substr(trim((string)($input['name']??'')),0,255);$availability=(string)($input['availability_status']??'available');$status=(string)($input['status']??'active');if($name==='')$errors[]='Equipment name is required.';if($unit===null||!$this->repository->relationExists('research_units',$unit)||!$this->repository->canUseUnit($userId,$unit))$errors[]='Choose a research unit within your scope.';if(trim((string)($input['facility_id']??''))!==''&&($facility===null||!$this->repository->relationExists('facilities',$facility)))$errors[]='Choose a valid facility.';if(!in_array($availability,self::AVAILABILITY,true))$errors[]='Choose a valid availability status.';if(!in_array($status,['active','inactive','archived'],true))$errors[]='Choose a valid equipment status.';return['data'=>['research_unit_id'=>$unit,'facility_id'=>$facility,'name'=>$name,'manufacturer'=>$this->nullable($input['manufacturer']??null,180),'model'=>$this->nullable($input['model']??null,120),'asset_reference'=>$this->nullable($input['asset_reference']??null,100),'capabilities'=>$this->nullable($input['capabilities']??null,100000),'availability_status'=>$availability,'external_use_allowed'=>($input['external_use_allowed']??'')==='1'?1:0,'booking_information'=>$this->nullable($input['booking_information']??null,20000),'status'=>$status],'errors'=>$errors];}
    private function id(mixed$value):?int{$value=trim((string)$value);return ctype_digit($value)&&(int)$value>0?(int)$value:null;}
    private function nullable(mixed$value,int$max):?string{$value=mb_substr(trim((string)$value),0,$max);return$value===''?null:$value;}
    private function slug(string$value,string$fallback):string{$value=trim($value)!==''?$value:$fallback;$ascii=iconv('UTF-8','ASCII//TRANSLIT//IGNORE',$value);return trim(strtolower((string)preg_replace('/[^a-zA-Z0-9]+/','-',is_string($ascii)?$ascii:$value)),'-');}
}
