<?php declare(strict_types=1); use FastWebsite\Core\View; ?>
<section class="admin-page-heading">
    <div><p class="eyebrow">Phase 7 metadata</p><h1>Research metadata</h1><p>Maintain reusable research themes and partner organizations. The 17 SDGs are centrally seeded and ready for project assignment.</p></div>
    <div class="heading-actions"><a class="button button-secondary" href="<?=View::escape($baseUrl)?>admin/research">Research units</a><a class="button button-secondary" href="<?=View::escape($baseUrl)?>admin/research/projects">Projects</a></div>
</section>
<?php if (is_string($success) && $success !== ''): ?><div class="success-alert"><?=View::escape($success)?></div><?php endif; ?>
<section class="admin-summary-grid metadata-summary">
    <article><strong><?=count($themes)?></strong><span>Research themes</span></article>
    <article><strong><?=count($partners)?></strong><span>Partner organizations</span></article>
    <article><strong><?=count($sdgs)?></strong><span>Sustainable Development Goals</span></article>
</section>
<section class="admin-panel" id="themes">
    <div class="panel-heading"><div><p class="eyebrow">Reusable taxonomy</p><h2>Research themes</h2></div><?php if ($canCreate): ?><a class="button button-primary" href="<?=View::escape($baseUrl)?>admin/research/metadata/themes/create">Add theme</a><?php endif; ?></div>
    <?php if ($themes === []): ?><p class="admin-empty">No research themes yet. Create the reviewed FAST theme catalogue here.</p><?php else: ?>
    <div class="table-scroll"><table class="admin-table"><thead><tr><th>Theme</th><th>Lead department</th><th>Status</th><th>Actions</th></tr></thead><tbody>
    <?php foreach ($themes as $theme): ?><tr><th><?=View::escape($theme['name'])?><small><?=View::escape($theme['parent_name'] ? 'Under '.$theme['parent_name'] : $theme['slug'])?></small></th><td><?=View::escape($theme['department_names'] ?? 'Not assigned')?></td><td><span class="status-badge status-<?=View::escape($theme['status'])?>"><?=View::escape(ucfirst(str_replace('_', ' ', $theme['status'])))?></span></td><td><div class="table-actions"><?php if ($canEdit): ?><a class="button button-secondary button-compact" href="<?=View::escape($baseUrl)?>admin/research/metadata/themes/<?=(int)$theme['id']?>/edit">Edit</a><form method="post" action="<?=View::escape($baseUrl)?>admin/research/metadata/themes/<?=(int)$theme['id']?>/workflow"><input type="hidden" name="_token" value="<?=View::escape($csrfToken)?>"><?php if ($theme['status'] === 'published'): ?><button class="button button-secondary button-compact" name="action" value="archive">Archive</button><?php elseif ($theme['status'] === 'archived'): ?><button class="button button-secondary button-compact" name="action" value="restore">Restore draft</button><?php else: ?><button class="button button-primary button-compact" name="action" value="publish">Publish</button><?php endif; ?></form><?php endif; ?></div></td></tr><?php endforeach; ?>
    </tbody></table></div><?php endif; ?>
</section>
<section class="admin-panel" id="partners">
    <div class="panel-heading"><div><p class="eyebrow">Reusable organizations</p><h2>Research partners</h2></div><?php if ($canCreate): ?><a class="button button-primary" href="<?=View::escape($baseUrl)?>admin/research/metadata/partners/create">Add partner</a><?php endif; ?></div>
    <?php if ($partners === []): ?><p class="admin-empty">No partner organizations yet. Add only approved institutional relationships.</p><?php else: ?>
    <div class="table-scroll"><table class="admin-table"><thead><tr><th>Partner</th><th>Type</th><th>Country</th><th>Status</th><th>Actions</th></tr></thead><tbody>
    <?php foreach ($partners as $partner): ?><tr><th><?=View::escape($partner['name'])?></th><td><?=View::escape(ucwords(str_replace('_', ' ', $partner['partner_type'])))?></td><td><?=View::escape($partner['country'] ?? 'Not set')?></td><td><span class="status-badge status-<?=View::escape($partner['status'])?>"><?=View::escape(ucfirst(str_replace('_', ' ', $partner['status'])))?></span></td><td><div class="table-actions"><?php if ($canEdit): ?><a class="button button-secondary button-compact" href="<?=View::escape($baseUrl)?>admin/research/metadata/partners/<?=(int)$partner['id']?>/edit">Edit</a><form method="post" action="<?=View::escape($baseUrl)?>admin/research/metadata/partners/<?=(int)$partner['id']?>/workflow"><input type="hidden" name="_token" value="<?=View::escape($csrfToken)?>"><?php if ($partner['status'] === 'published'): ?><button class="button button-secondary button-compact" name="action" value="archive">Archive</button><?php elseif ($partner['status'] === 'archived'): ?><button class="button button-secondary button-compact" name="action" value="restore">Restore draft</button><?php else: ?><button class="button button-primary button-compact" name="action" value="publish">Publish</button><?php endif; ?></form><?php endif; ?></div></td></tr><?php endforeach; ?>
    </tbody></table></div><?php endif; ?>
</section>
<section class="admin-panel" id="sdgs"><div class="panel-heading"><div><p class="eyebrow">Official global framework</p><h2>Sustainable Development Goals</h2></div></div><div class="metadata-chip-grid"><?php foreach ($sdgs as $sdg): ?><span class="metadata-chip sdg-chip" style="--chip-colour:<?=View::escape($sdg['colour_code'] ?: '#425466')?>"><strong><?=View::escape($sdg['code'])?></strong> <?=View::escape($sdg['name'])?></span><?php endforeach; ?></div></section>
