<?php
declare(strict_types=1);
use FastWebsite\Core\View;

$defaults = [
    'version_id' => $version['id'] ?? '',
    'version_name' => $version['version_name'] ?? 'Undergraduate Handbook 2025/2026',
    'effective_year' => $version['effective_year'] ?? '2025',
    'approval_reference' => $version['approval_reference'] ?? '',
    'approval_date' => $version['approval_date'] ?? '',
    'placement_id' => $editing['placement_id'] ?? '',
    'course_id' => $editing['course_id'] ?? '',
    'course_code' => $editing['course_code'] ?? '',
    'title' => $editing['title'] ?? '',
    'description' => $editing['description'] ?? '',
    'credit_units' => $editing['credit_units_override'] ?? ($editing['default_credit_units'] ?? ''),
    'study_year' => $editing['study_year'] ?? '1',
    'semester' => $editing['semester'] ?? '1',
    'requirement_type' => $editing['requirement_type'] ?? 'core',
    'display_order' => $editing['display_order'] ?? '0',
];
$form = array_merge($defaults, $values);
$groups = [];
foreach ($placements as $placement) {
    $groups[(int) $placement['study_year']][(int) $placement['semester']][] = $placement;
}
$semesterName = static fn (int $semester): string => $semester === 3 ? 'Recess term' : 'Semester ' . $semester;
?>
<section class="admin-page-heading"><div><p class="eyebrow">Programme curriculum</p><h1><?= View::escape($programme['name']) ?></h1><?php if ($version): ?><span class="status-badge status-<?= View::escape($version['status']) ?>"><?= View::escape(ucfirst($version['status'])) ?></span><?php endif; ?></div><div class="heading-actions"><a class="button button-secondary" href="<?= View::escape($baseUrl) ?>admin/programmes/<?= (int) $programme['id'] ?>">Programme details</a><?php if ($version && $placements && $canPublish && $version['status'] !== 'published'): ?><form method="post" action="<?= View::escape($baseUrl) ?>admin/programmes/<?= (int) $programme['id'] ?>/curriculum/<?= (int) $version['id'] ?>/publish"><input type="hidden" name="_token" value="<?= View::escape($csrfToken) ?>"><button class="button button-primary publish-button" type="submit">Publish curriculum</button></form><?php endif; ?></div></section>
<?php if (is_string($success) && $success !== ''): ?><div class="success-alert" role="status"><?= View::escape($success) ?></div><?php endif; ?>
<?php if ($errors): ?><div class="form-alert" role="alert"><strong>Please correct the following:</strong><ul><?php foreach ($errors as $error): ?><li><?= View::escape($error) ?></li><?php endforeach; ?></ul></div><?php endif; ?>
<div class="record-grid curriculum-admin-grid"><div class="record-main">
<?php if (!$placements): ?><section class="admin-panel"><p class="admin-empty">No courses have been added yet. Use the form to add the first course; the curriculum version will be created automatically.</p></section><?php endif; ?>
<?php foreach ($groups as $year => $semesters): ?><section class="admin-panel curriculum-year"><h2>Year <?= $year ?></h2><?php foreach ($semesters as $semester => $courses): ?><h3><?= $semesterName($semester) ?></h3><div class="table-wrap"><table class="admin-table curriculum-table"><thead><tr><th>Code</th><th>Course</th><th>Type</th><th>CU</th><th></th></tr></thead><tbody><?php foreach ($courses as $course): ?><tr><td><strong><?= View::escape($course['course_code']) ?></strong></td><td><?= View::escape($course['title']) ?></td><td><?= View::escape(ucfirst($course['requirement_type'])) ?></td><td><?= View::escape(rtrim(rtrim((string) ($course['credit_units_override'] ?? $course['default_credit_units']), '0'), '.')) ?></td><td class="table-actions"><a class="button button-small button-secondary" href="<?= View::escape($baseUrl) ?>admin/programmes/<?= (int) $programme['id'] ?>/curriculum?edit=<?= (int) $course['placement_id'] ?>#course-editor">Edit</a><form method="post" action="<?= View::escape($baseUrl) ?>admin/programmes/<?= (int) $programme['id'] ?>/curriculum/<?= (int) $version['id'] ?>/placements/<?= (int) $course['placement_id'] ?>/delete" onsubmit="return confirm('Remove this course from the curriculum?')"><input type="hidden" name="_token" value="<?= View::escape($csrfToken) ?>"><button class="button button-small button-secondary" type="submit">Remove</button></form></td></tr><?php endforeach; ?></tbody></table></div><?php endforeach; ?></section><?php endforeach; ?>
</div><aside class="record-sidebar"><section class="admin-panel" id="course-editor"><h2><?= $editing ? 'Edit course' : 'Add a course' ?></h2><p class="form-help"><?= $version && $version['status'] === 'published' ? 'This curriculum is live. Authorized changes update the public programme page immediately.' : 'Save courses as you work, then publish the complete curriculum.' ?></p><form class="content-form" method="post" action="<?= View::escape($baseUrl) ?>admin/programmes/<?= (int) $programme['id'] ?>/curriculum/courses">
<input type="hidden" name="_token" value="<?= View::escape($csrfToken) ?>"><input type="hidden" name="version_id" value="<?= View::escape((string) $form['version_id']) ?>"><input type="hidden" name="placement_id" value="<?= View::escape((string) $form['placement_id']) ?>"><input type="hidden" name="course_id" value="<?= View::escape((string) $form['course_id']) ?>">
<fieldset><legend>Curriculum version</legend><div class="form-field"><label for="version-name">Version name</label><input id="version-name" name="version_name" maxlength="120" required value="<?= View::escape((string) $form['version_name']) ?>"></div><div class="form-row"><div class="form-field"><label for="effective-year">Effective year</label><input id="effective-year" name="effective_year" type="number" min="2000" max="2200" required value="<?= View::escape((string) $form['effective_year']) ?>"></div><div class="form-field"><label for="approval-date">Approval date</label><input id="approval-date" name="approval_date" type="date" value="<?= View::escape((string) $form['approval_date']) ?>"></div></div><div class="form-field"><label for="approval-reference">Approval reference</label><input id="approval-reference" name="approval_reference" maxlength="150" value="<?= View::escape((string) $form['approval_reference']) ?>"></div></fieldset>
<fieldset><legend>Course details</legend><div class="form-row"><div class="form-field"><label for="course-code">Course code</label><input id="course-code" name="course_code" maxlength="50" required value="<?= View::escape((string) $form['course_code']) ?>"></div><div class="form-field"><label for="credit-units">Credit units</label><input id="credit-units" name="credit_units" type="number" step="0.5" min="0.5" max="30" required value="<?= View::escape((string) $form['credit_units']) ?>"></div></div><div class="form-field"><label for="course-title">Course title</label><input id="course-title" name="title" maxlength="255" required value="<?= View::escape((string) $form['title']) ?>"></div><div class="form-field"><label for="course-description">Description <span>(optional)</span></label><textarea id="course-description" name="description" rows="4"><?= View::escape((string) $form['description']) ?></textarea></div></fieldset>
<fieldset><legend>Placement</legend><div class="form-row"><div class="form-field"><label for="study-year">Year</label><input id="study-year" name="study_year" type="number" min="1" max="10" required value="<?= View::escape((string) $form['study_year']) ?>"></div><div class="form-field"><label for="semester">Semester</label><select id="semester" name="semester"><?php foreach ([1=>'Semester 1',2=>'Semester 2',3=>'Recess term'] as $value=>$label): ?><option value="<?= $value ?>"<?= (int) $form['semester'] === $value ? ' selected' : '' ?>><?= $label ?></option><?php endforeach; ?></select></div></div><div class="form-row"><div class="form-field"><label for="requirement-type">Requirement</label><select id="requirement-type" name="requirement_type"><?php foreach (['core','elective','optional','audited'] as $type): ?><option value="<?= $type ?>"<?= $form['requirement_type'] === $type ? ' selected' : '' ?>><?= ucfirst($type) ?></option><?php endforeach; ?></select></div><div class="form-field"><label for="display-order">Display order</label><input id="display-order" name="display_order" type="number" min="0" max="1000" value="<?= View::escape((string) $form['display_order']) ?>"></div></div></fieldset>
<div class="form-actions"><button class="button button-primary" type="submit"><?= $editing ? 'Save changes' : 'Add course' ?></button><?php if ($editing): ?><a class="button button-secondary" href="<?= View::escape($baseUrl) ?>admin/programmes/<?= (int) $programme['id'] ?>/curriculum#course-editor">Cancel</a><?php endif; ?></div></form></section></aside></div>
