<?php
declare(strict_types=1);
use FastWebsite\Core\View;
$value = static fn (string $field): string => (string) ($values[$field] ?? '');
$editing = is_int($programmeId);
$published = $editing && $currentStatus === 'published';
$action = $editing ? $baseUrl . 'admin/programmes/' . $programmeId : $baseUrl . 'admin/programmes';
?>
<section class="admin-page-heading"><div><p class="eyebrow"><?= $published ? 'Live programme' : ($editing ? 'Programme revision' : 'New programme draft') ?></p><h1><?= $editing ? 'Edit programme' : 'Create programme' ?></h1><p><?= $published ? 'The programme stays public while you edit. Saving applies changes immediately.' : 'Build the public programme page and publish it when ready.' ?></p></div><a class="button button-secondary" href="<?= View::escape($baseUrl) ?>admin/programmes<?= $editing ? '/' . $programmeId : '' ?>">Cancel</a></section>
<?php if ($errors !== []): ?><div class="form-alert" role="alert"><strong>Please correct the following:</strong><ul><?php foreach ($errors as $error): ?><li><?= View::escape($error) ?></li><?php endforeach; ?></ul></div><?php endif; ?>
<?php if ($published): ?><div class="success-alert live-edit-notice" role="status"><strong>Editing published content.</strong> The current page stays online until you select “Save published changes”.</div><?php endif; ?>
<form class="content-form" method="post" enctype="multipart/form-data" action="<?= View::escape($action) ?>">
<input type="hidden" name="_token" value="<?= View::escape($csrfToken) ?>"><input type="hidden" name="MAX_FILE_SIZE" value="20971520">
<section class="form-section"><div class="form-section-heading"><h2>Programme identity</h2><p>Name, ownership, qualification level, and public URL.</p></div><div class="form-grid">
    <div class="form-field span-2"><label for="name">Programme name *</label><input id="name" name="name" maxlength="255" required value="<?= View::escape($value('name')) ?>"></div>
    <div class="form-field"><label for="programme_code">Programme code</label><input id="programme_code" name="programme_code" maxlength="50" value="<?= View::escape($value('programme_code')) ?>"></div>
    <div class="form-field"><label for="award_title">Award title</label><input id="award_title" name="award_title" maxlength="255" value="<?= View::escape($value('award_title')) ?>"></div>
    <div class="form-field"><label for="programme_level_id">Level *</label><select id="programme_level_id" name="programme_level_id" required><?php foreach ($levels as $level): ?><option value="<?= (int) $level['id'] ?>" <?= $value('programme_level_id') === (string) $level['id'] ? 'selected' : '' ?>><?= View::escape($level['name']) ?></option><?php endforeach; ?></select></div>
    <div class="form-field"><label for="department_id">Lead department *</label><select id="department_id" name="department_id" required><?php foreach ($departments as $department): ?><option value="<?= (int) $department['id'] ?>" <?= $value('department_id') === (string) $department['id'] ? 'selected' : '' ?>><?= View::escape($department['name']) ?></option><?php endforeach; ?></select></div>
    <div class="form-field span-2"><label for="slug">Programme URL</label><input id="slug" name="slug" maxlength="280" pattern="[a-z0-9]+(?:-[a-z0-9]+)*" value="<?= View::escape($value('slug')) ?>"><p class="field-guidance">Leave blank to generate it from the programme name.</p></div>
</div></section>
<section class="form-section"><div class="form-section-heading"><h2>Study details</h2></div><div class="form-grid">
    <div class="form-field"><label for="duration_text">Duration label</label><input id="duration_text" name="duration_text" maxlength="100" value="<?= View::escape($value('duration_text')) ?>" placeholder="Three years"></div>
    <div class="form-field"><label for="duration_years">Duration in years</label><input id="duration_years" name="duration_years" type="number" min="0.1" max="99.9" step="0.1" value="<?= View::escape($value('duration_years')) ?>"></div>
    <div class="form-field"><label for="study_mode">Study mode</label><select id="study_mode" name="study_mode"><?php foreach (['full_time'=>'Full time','part_time'=>'Part time','both'=>'Full and part time','other'=>'Other'] as $key=>$label): ?><option value="<?= $key ?>" <?= $value('study_mode') === $key ? 'selected' : '' ?>><?= $label ?></option><?php endforeach; ?></select></div>
    <div class="form-field"><label for="delivery_mode">Delivery mode</label><select id="delivery_mode" name="delivery_mode"><?php foreach (['face_to_face'=>'Face to face','online'=>'Online','blended'=>'Blended','other'=>'Other'] as $key=>$label): ?><option value="<?= $key ?>" <?= $value('delivery_mode') === $key ? 'selected' : '' ?>><?= $label ?></option><?php endforeach; ?></select></div>
    <div class="form-field span-2"><label for="application_url">Application URL</label><input id="application_url" name="application_url" type="url" maxlength="500" value="<?= View::escape($value('application_url')) ?>" placeholder="https://"></div>
    <div class="form-field"><label for="display_order">Display order</label><input id="display_order" name="display_order" type="number" min="0" max="65535" value="<?= View::escape($value('display_order')) ?>"></div>
</div></section>
<section class="form-section"><div class="form-section-heading"><h2>Hero image</h2><p>Reuse an existing image or upload a new one.</p></div><div class="form-grid">
    <div class="form-field span-2"><label for="hero_media_id">Existing image</label><select id="hero_media_id" name="hero_media_id" data-media-upload="<?= View::escape($baseUrl) ?>admin/media"><option value="">No image</option><?php foreach ($images as $image): ?><option value="<?= (int) $image['id'] ?>" <?= $value('hero_media_id') === (string) $image['id'] ? 'selected' : '' ?>><?= View::escape($image['original_name']) ?></option><?php endforeach; ?></select></div>
    <div class="form-field span-2 upload-field"><label for="hero_image">Upload image</label><input id="hero_image" name="hero_image" type="file" accept="image/jpeg,image/png,image/webp,image/gif"><p class="field-guidance">JPEG, PNG, WebP, or GIF; maximum 20 MB.</p></div>
    <div class="form-field span-2"><label for="hero_alt_text">Image description</label><input id="hero_alt_text" name="hero_alt_text" maxlength="255" value="<?= View::escape($value('hero_alt_text')) ?>"><p class="field-guidance">Required for a new upload.</p></div>
</div></section>
<section class="form-section"><div class="form-section-heading"><h2>Public content</h2><p>An overview is required before publication.</p></div><div class="form-grid">
<?php foreach (['overview'=>'Overview','why_study'=>'Why study this programme','objectives'=>'Objectives','learning_outcomes'=>'Learning outcomes','entry_requirements'=>'Entry requirements','career_opportunities'=>'Career opportunities','practical_training'=>'Practical training','accreditation'=>'Accreditation'] as $field=>$label): ?><div class="form-field span-2"><label for="<?= $field ?>"><?= $label ?><?= $field === 'overview' ? ' * for publishing' : '' ?></label><textarea id="<?= $field ?>" name="<?= $field ?>" rows="<?= $field === 'overview' ? 5 : 7 ?>"><?= View::escape($value($field)) ?></textarea></div><?php endforeach; ?>
</div></section>
<?php if ($editing): ?><section class="form-section"><div class="form-field"><label for="revision_note">Revision note</label><textarea id="revision_note" name="revision_note" rows="3"><?= View::escape($revisionNote) ?></textarea></div></section><?php endif; ?>
<div class="form-actions"><?php if ($published): ?><button class="button button-primary publish-button" type="submit" name="submit_action" value="save_live">Save published changes</button><?php else: ?><button class="button <?= $canPublishDirectly ? 'button-secondary' : 'button-primary' ?>" type="submit" name="submit_action" value="save"><?= $editing ? 'Save revision' : 'Create draft' ?></button><?php if ($canPublishDirectly): ?><button class="button button-primary publish-button" type="submit" name="submit_action" value="publish"><?= $editing ? 'Save and publish' : 'Create and publish' ?></button><?php endif; ?><?php endif; ?><a class="button button-secondary" href="<?= View::escape($baseUrl) ?>admin/programmes<?= $editing ? '/' . $programmeId : '' ?>">Cancel</a></div>
</form>
