<?php
declare(strict_types=1);
use FastWebsite\Core\View;
$path = is_string($programme['hero_path']) ? str_replace('\\', '/', $programme['hero_path']) : '';
$image = $path !== '' && preg_match('#^(?:https?:)?//#i', $path) !== 1 ? $baseUrl . ltrim(preg_replace('#^public/#', '', $path) ?? $path, '/') : null;
?>
<section class="admin-page-heading"><div><p class="eyebrow"><?= View::escape($programme['level_name']) ?></p><h1><?= View::escape($programme['name']) ?></h1><span class="status-badge status-<?= View::escape($programme['status']) ?>"><?= View::escape(ucfirst(str_replace('_', ' ', $programme['status']))) ?></span></div><div class="heading-actions"><a class="button button-secondary" href="<?= View::escape($baseUrl) ?>admin/programmes">All programmes</a><a class="button button-secondary" href="<?= View::escape($baseUrl) ?>admin/programmes/<?= (int) $programme['id'] ?>/curriculum">Manage curriculum</a><?php if ($canEdit): ?><a class="button <?= $canQuickPublish ? 'button-secondary' : 'button-primary' ?>" href="<?= View::escape($baseUrl) ?>admin/programmes/<?= (int) $programme['id'] ?>/edit">Edit</a><?php endif; ?><?php if ($canQuickPublish): ?><form class="quick-publish-form" method="post" action="<?= View::escape($baseUrl) ?>admin/programmes/<?= (int) $programme['id'] ?>/workflow"><input type="hidden" name="_token" value="<?= View::escape($csrfToken) ?>"><input type="hidden" name="action" value="publish_now"><button class="button button-primary publish-button" type="submit">Publish now</button></form><?php endif; ?></div></section>
<?php if (is_string($success) && $success !== ''): ?><div class="success-alert" role="status"><?= View::escape($success) ?></div><?php endif; ?>
<?php if ($needsOverviewToPublish): ?><div class="form-alert publish-guidance" role="status"><strong>Ready to publish?</strong> Add an overview while editing, then use “Save and publish”.</div><?php endif; ?>
<div class="record-grid"><div class="record-main">
<?php if ($image): ?><section class="admin-panel record-hero"><img src="<?= View::escape($image) ?>" alt="<?= View::escape($programme['hero_alt_text'] ?: $programme['name']) ?>"></section><?php endif; ?>
<?php foreach (['Overview'=>'overview','Why study'=>'why_study','Objectives'=>'objectives','Learning outcomes'=>'learning_outcomes','Entry requirements'=>'entry_requirements','Career opportunities'=>'career_opportunities','Practical training'=>'practical_training','Accreditation'=>'accreditation'] as $heading=>$field): ?><?php if (is_string($programme[$field]) && trim($programme[$field]) !== ''): ?><section class="admin-panel record-section"><h2><?= $heading ?></h2><div class="prose"><?= nl2br(View::escape($programme[$field])) ?></div></section><?php endif; ?><?php endforeach; ?>
</div><aside class="record-sidebar"><section class="admin-panel"><h2>Programme details</h2><dl class="detail-list"><div><dt>Code</dt><dd><?= View::escape($programme['programme_code'] ?? 'Not set') ?></dd></div><div><dt>Lead department</dt><dd><?= View::escape($programme['department_name'] ?? 'Not set') ?></dd></div><div><dt>Duration</dt><dd><?= View::escape($programme['duration_text'] ?? ($programme['duration_years'] ? $programme['duration_years'] . ' years' : 'Not set')) ?></dd></div><div><dt>Public URL</dt><dd>/programmes/<?= View::escape($programme['slug']) ?></dd></div></dl></section>
<?php if ($actions !== []): ?><section class="admin-panel"><h2>Workflow action</h2><form class="workflow-form" method="post" action="<?= View::escape($baseUrl) ?>admin/programmes/<?= (int) $programme['id'] ?>/workflow"><input type="hidden" name="_token" value="<?= View::escape($csrfToken) ?>"><div class="form-field"><label for="programme-comment">Comment</label><textarea id="programme-comment" name="comment" rows="3"></textarea></div><div class="workflow-actions"><?php foreach ($actions as $action): ?><button class="button <?= $action['action'] === 'published' ? 'button-primary' : 'button-secondary' ?>" type="submit" name="action" value="<?= View::escape($action['action']) ?>"><?= View::escape($action['label']) ?></button><?php endforeach; ?></div></form></section><?php endif; ?>
<section class="admin-panel"><h2>Workflow history</h2><?php if ($history === []): ?><p class="admin-empty compact">No actions yet.</p><?php else: ?><ol class="history-list"><?php foreach ($history as $entry): ?><li><strong><?= View::escape(ucfirst(str_replace('_', ' ', $entry['action']))) ?></strong><span><?= View::escape($entry['actor_name'] ?? 'Former user') ?></span></li><?php endforeach; ?></ol><?php endif; ?></section></aside></div>
