<?php

declare(strict_types=1);

use FastWebsite\Core\Database;use FastWebsite\Repositories\AssetRepository;use FastWebsite\Repositories\SiteContentRepository;use FastWebsite\Repositories\UserRepository;use FastWebsite\Services\AuthorizationService;use FastWebsite\Services\DepartmentScopeService;use FastWebsite\Validation\SiteContentValidator;

return static function():void{
    /** @var Database $database */$database=require dirname(__DIR__,2).'/bootstrap/database.php';$pdo=$database->connection();$pdo->beginTransaction();
    try{$suffix=bin2hex(random_bytes(5));$user=(int)$pdo->query('SELECT id FROM users WHERE is_active=1 AND deleted_at IS NULL ORDER BY id LIMIT 1')->fetchColumn();$department=(int)$pdo->query('SELECT id FROM departments WHERE deleted_at IS NULL ORDER BY id LIMIT 1')->fetchColumn();$newsCategory=(int)$pdo->query('SELECT id FROM news_categories WHERE is_active=1 ORDER BY id LIMIT 1')->fetchColumn();$eventCategory=(int)$pdo->query('SELECT id FROM event_categories WHERE is_active=1 ORDER BY id LIMIT 1')->fetchColumn();if(min($user,$department,$newsCategory,$eventCategory)<1)throw new RuntimeException('MVP content prerequisites are missing.');$users=new UserRepository($database);$auth=new AuthorizationService($users);$scope=new DepartmentScopeService($users,$auth);$content=new SiteContentRepository($database,$scope);$validator=new SiteContentValidator($content);
        $news=$validator->news(['category_id'=>(string)$newsCategory,'department_id'=>(string)$department,'title'=>'Transactional news '.$suffix,'slug'=>'transactional-news-'.$suffix,'summary'=>'Summary','body'=>'Body','article_date'=>'2026-08-01','allow_sharing'=>'1'],$user);if($news['errors']!==[])throw new RuntimeException('Valid news rejected: '.json_encode($news['errors']));$newsId=$content->saveNews(null,$news['data'],$news['department_id']);$content->newsStatus($newsId,'published');if($content->publicNews('transactional-news-'.$suffix)===null)throw new RuntimeException('Published news is not public.');$content->newsStatus($newsId,'archived');if($content->publicNews('transactional-news-'.$suffix)!==null)throw new RuntimeException('Archived news remained public.');
        $event=$validator->event(['category_id'=>(string)$eventCategory,'department_id'=>(string)$department,'title'=>'Transactional event '.$suffix,'slug'=>'transactional-event-'.$suffix,'starts_at'=>'2026-09-01T10:00','ends_at'=>'2026-09-01T12:00','event_status'=>'scheduled'],$user);if($event['errors']!==[])throw new RuntimeException('Valid event rejected: '.json_encode($event['errors']));$eventId=$content->saveEvent(null,$event['data'],$event['department_id']);$content->eventStatus($eventId,'published');if($content->publicEvent('transactional-event-'.$suffix)===null)throw new RuntimeException('Published event is not public.');
        $page=$validator->page(['title'=>'Transactional page '.$suffix,'slug'=>'transactional-page-'.$suffix,'page_template'=>'standard','show_in_navigation'=>'1']);if($page['errors']!==[])throw new RuntimeException('Valid page rejected.');$pageId=$content->savePage(null,$page['data']);$section=$validator->section(['section_type'=>'rich_text','heading'=>'Test heading','body'=>'Test body','display_order'=>'1','is_visible'=>'1']);$content->addSection($pageId,$section['data']);$content->pageStatus($pageId,'published');if($content->publicPage('transactional-page-'.$suffix)===null||count($content->sections($pageId,true))!==1)throw new RuntimeException('Published page or section is missing.');
        $assets=new AssetRepository($database);$docId=$assets->saveDocument(null,['document_type_id'=>null,'title'=>'Transactional document '.$suffix,'description'=>'Test','original_name'=>'test.pdf','stored_name'=>$suffix.'.pdf','file_path'=>'public/uploads/documents/test/'.$suffix.'.pdf','mime_type'=>'application/pdf','file_size'=>100,'version_label'=>'1','effective_date'=>'2026-08-01','review_date'=>null,'is_public'=>1,'uploaded_by'=>$user]);$assets->documentStatus($docId,'published');$public=array_filter($assets->documents(true),static fn(array$d):bool=>(int)$d['id']===$docId);if(count($public)!==1)throw new RuntimeException('Published public document is missing.');$assets->documentStatus($docId,'archived');$public=array_filter($assets->documents(true),static fn(array$d):bool=>(int)$d['id']===$docId);if($public!==[])throw new RuntimeException('Archived document remained public.');
    }finally{if($pdo->inTransaction())$pdo->rollBack();}
};
