<?php
declare(strict_types=1);
use FastWebsite\Core\View;
$path = is_string($programme['hero_path']) ? str_replace('\\', '/', $programme['hero_path']) : '';
$image = $path !== '' && preg_match('#^(?:https?:)?//#i', $path) !== 1 ? $baseUrl . ltrim(preg_replace('#^public/#', '', $path) ?? $path, '/') : null;
$duration = $programme['duration_text'] ?: ($programme['duration_years'] ? $programme['duration_years'] . ' years' : null);
?>
<section class="department-hero<?= $image ? ' has-image' : '' ?>"<?php if ($image): ?> style="--hero-image: url('<?= View::escape($image) ?>')"<?php endif; ?>><div class="shell"><a class="back-link" href="<?= View::escape($baseUrl) ?>programmes">← Academic programmes</a><p class="eyebrow"><?= View::escape($programme['level_name']) ?></p><h1><?= View::escape($programme['name']) ?></h1><?php if ($programme['award_title']): ?><p class="lead"><?= View::escape($programme['award_title']) ?></p><?php endif; ?></div></section>
<section class="section"><div class="shell public-record-grid"><div class="public-record-main">
<?php foreach (['Overview'=>'overview','Why study this programme'=>'why_study','Objectives'=>'objectives','Learning outcomes'=>'learning_outcomes','Entry requirements'=>'entry_requirements','Career opportunities'=>'career_opportunities','Practical training'=>'practical_training','Accreditation'=>'accreditation'] as $heading=>$field): ?><?php if (is_string($programme[$field]) && trim($programme[$field]) !== ''): ?><section class="public-content-section"><h2><?= $heading ?></h2><div class="prose"><?= View::richText($programme[$field]) ?></div></section><?php endif; ?><?php endforeach; ?>
<?php if ($curriculum && $curriculumCourses): ?><?php $curriculumGroups = []; foreach ($curriculumCourses as $course) { $curriculumGroups[(int) $course['study_year']][(int) $course['semester']][] = $course; } ?><section class="public-content-section programme-curriculum"><p class="eyebrow">Curriculum</p><h2>Course structure</h2><p><?= View::escape($curriculum['version_name']) ?><?php if ($curriculum['total_credit_units'] !== null): ?> · <?= View::escape(rtrim(rtrim((string) $curriculum['total_credit_units'], '0'), '.')) ?> total credit units<?php endif; ?></p><?php foreach ($curriculumGroups as $year => $semesters): ?><div class="curriculum-year"><h3>Year <?= $year ?></h3><?php foreach ($semesters as $semester => $courses): ?><h4><?= $semester === 3 ? 'Recess term' : 'Semester ' . $semester ?></h4><div class="table-wrap"><table class="curriculum-table"><thead><tr><th>Code</th><th>Course</th><th>Type</th><th>CU</th></tr></thead><tbody><?php foreach ($courses as $course): ?><tr><td><strong><?= View::escape($course['course_code']) ?></strong></td><td><?= View::escape($course['title']) ?></td><td><?= View::escape(ucfirst($course['requirement_type'])) ?></td><td><?= View::escape(rtrim(rtrim((string) ($course['credit_units_override'] ?? $course['default_credit_units']), '0'), '.')) ?></td></tr><?php endforeach; ?></tbody></table></div><?php endforeach; ?></div><?php endforeach; ?></section><?php endif; ?>
</div><aside class="public-contact-card"><p class="eyebrow">At a glance</p><h2><?= View::escape($programme['programme_code'] ?? $programme['level_name']) ?></h2><?php if ($duration): ?><p><strong>Duration</strong><br><?= View::escape($duration) ?></p><?php endif; ?><p><strong>Study mode</strong><br><?= View::escape(ucwords(str_replace('_', ' ', $programme['study_mode']))) ?></p><p><strong>Delivery</strong><br><?= View::escape(ucwords(str_replace('_', ' ', $programme['delivery_mode']))) ?></p><?php if ($programme['department_name']): ?><p><strong>Lead department</strong><br><?php if ($programme['department_slug']): ?><a href="<?= View::escape($baseUrl) ?>departments/<?= View::escape($programme['department_slug']) ?>"><?= View::escape($programme['department_name']) ?></a><?php else: ?><?= View::escape($programme['department_name']) ?><?php endif; ?></p><?php endif; ?><?php if ($programme['application_url']): ?><p><a class="button button-primary" href="<?= View::escape($programme['application_url']) ?>">Apply for this programme</a></p><?php endif; ?></aside></div></section>
