<?php

declare(strict_types=1);

use FastWebsite\Core\View;

$name = trim(implode(' ', array_filter([$profile['honorific_title'] ?? null, $profile['first_name'] ?? null, $profile['middle_name'] ?? null, $profile['last_name'] ?? null])));
if (trim((string) ($profile['post_nominals'] ?? '')) !== '') $name .= ', ' . trim((string) $profile['post_nominals']);
$path = is_string($profile['profile_path'] ?? null) ? str_replace('\\', '/', $profile['profile_path']) : '';
$image = $path !== '' && preg_match('#^(?:https?:)?//#i', $path) !== 1 ? $baseUrl . ltrim(preg_replace('#^public/#', '', $path) ?? $path, '/') : null;
$initials = mb_strtoupper(mb_substr((string) ($profile['first_name'] ?? ''), 0, 1) . mb_substr((string) ($profile['last_name'] ?? ''), 0, 1));
$position = trim((string) ($profile['position_title'] ?? '')) ?: ucfirst((string) ($profile['staff_category'] ?? 'Staff'));
$unit = trim((string) ($profile['department_name'] ?? '')) ?: trim((string) ($profile['faculty_name'] ?? 'FAST'));
$officeRoom = trim((string) ($profile['office_room'] ?? '')) ?: trim((string) ($profile['room'] ?? ''));
$workAddress = implode(', ', array_filter([trim((string) ($profile['building'] ?? '')), trim((string) ($profile['campus'] ?? ''))]));
$linkLabels = ['orcid' => 'ORCID', 'google_scholar' => 'Google Scholar', 'researchgate' => 'ResearchGate', 'linkedin' => 'LinkedIn', 'institutional_repository' => 'Institutional repository', 'personal_website' => 'Personal website', 'other' => 'External profile'];
$about = trim((string) ($profile['biography'] ?? '')) !== '' ? (string) $profile['biography'] : (string) ($profile['short_biography'] ?? '');
$tabs = ['about' => 'About', 'qualifications' => 'Qualifications', 'publications' => 'Publications', 'projects' => 'Projects', 'supervision' => 'Supervision', 'more' => 'More'];
?>
<section class="staff-profile-directory">
    <div class="shell staff-profile-directory-grid">
        <aside class="staff-profile-sidebar" aria-label="Staff profile summary">
            <a class="staff-profile-back" href="<?= View::escape($baseUrl) ?>staff">← Staff directory</a>
            <figure class="staff-profile-sidebar-portrait"><?php if ($image !== null): ?><img src="<?= View::escape($image) ?>" alt="<?= View::escape($profile['profile_alt_text'] ?: 'Portrait of ' . $name) ?>"><?php else: ?><span aria-hidden="true"><?= View::escape($initials) ?></span><?php endif; ?></figure>
            <div class="staff-profile-sidebar-heading"><h1><?= View::escape($name) ?></h1><p><?= View::escape($position) ?></p><?php if ((int) ($profile['supervision_available'] ?? 0) === 1): ?><span>Available for supervision</span><?php endif; ?></div>
            <div class="staff-profile-contact-card">
                <dl>
                    <div><dt>Faculty / Department / Office</dt><dd><?= View::escape($unit) ?></dd></div>
                    <?php if (!empty($profile['institutional_email'])): ?><div><dt>Work email</dt><dd><a href="mailto:<?= View::escape($profile['institutional_email']) ?>"><?= View::escape($profile['institutional_email']) ?></a></dd></div><?php endif; ?>
                    <?php if (!empty($profile['alternative_email'])): ?><div><dt>Alternative email</dt><dd><a href="mailto:<?= View::escape($profile['alternative_email']) ?>"><?= View::escape($profile['alternative_email']) ?></a></dd></div><?php endif; ?>
                    <?php if (!empty($profile['public_phone'])): ?><div><dt>Phone</dt><dd><a href="tel:<?= View::escape(preg_replace('/[^+0-9]/', '', (string) $profile['public_phone']) ?? '') ?>"><?= View::escape($profile['public_phone']) ?></a></dd></div><?php endif; ?>
                    <?php if ($officeRoom !== ''): ?><div><dt>Office room</dt><dd><?= View::escape($officeRoom) ?></dd></div><?php endif; ?>
                    <?php if ($workAddress !== ''): ?><div><dt>Work address</dt><dd><?= View::escape($workAddress) ?></dd></div><?php endif; ?>
                    <?php if (!empty($profile['consultation_hours'])): ?><div><dt>Consultation hours</dt><dd><?= View::escape($profile['consultation_hours']) ?></dd></div><?php endif; ?>
                </dl>
                <?php if ($links !== []): ?><div class="staff-profile-platforms"><strong>Research platforms</strong><?php foreach ($links as $link): ?><a href="<?= View::escape($link['url']) ?>" rel="noopener noreferrer"><?= View::escape($link['label'] ?: ($linkLabels[$link['link_type']] ?? 'External profile')) ?> <span aria-hidden="true">↗</span></a><?php endforeach; ?></div><?php endif; ?>
            </div>
        </aside>
        <div class="staff-profile-tabbed" data-profile-tabs>
            <div class="staff-profile-tab-list" role="tablist" aria-label="Staff profile sections"><?php foreach ($tabs as $tabId => $tabLabel): ?><button id="profile-tab-<?= $tabId ?>" type="button" role="tab" aria-controls="profile-panel-<?= $tabId ?>" aria-selected="<?= $tabId === 'about' ? 'true' : 'false' ?>" tabindex="<?= $tabId === 'about' ? '0' : '-1' ?>" data-profile-tab="<?= $tabId ?>"><?= $tabLabel ?></button><?php endforeach; ?></div>
            <div class="staff-profile-tab-panels">
                <section id="profile-panel-about" role="tabpanel" aria-labelledby="profile-tab-about" data-profile-panel="about"><p class="eyebrow">About <?= View::escape($profile['first_name']) ?></p><?php if (trim($about) !== ''): ?><div class="prose staff-profile-prose"><?= View::richText($about) ?></div><?php else: ?><p>This staff biography is being prepared.</p><?php endif; ?><?php if ($expertise !== []): ?><div class="staff-profile-panel-section"><h2>Areas of expertise</h2><ul class="staff-profile-expertise-list"><?php foreach ($expertise as $area): ?><li><?= View::escape($area['name']) ?></li><?php endforeach; ?></ul></div><?php endif; ?></section>
                <section id="profile-panel-qualifications" role="tabpanel" aria-labelledby="profile-tab-qualifications" data-profile-panel="qualifications" hidden><p class="eyebrow">Academic background</p><h2>Qualifications</h2><?php if ($qualifications !== []): ?><ol class="staff-profile-qualification-list"><?php foreach ($qualifications as $qualification): ?><li><strong><?= View::escape($qualification['qualification']) ?><?= !empty($qualification['field_of_study']) ? ' in ' . View::escape($qualification['field_of_study']) : '' ?></strong><?php $details = implode(', ', array_filter([$qualification['institution'], $qualification['country'], $qualification['completion_year']])); if ($details !== ''): ?><span><?= View::escape($details) ?></span><?php endif; ?></li><?php endforeach; ?></ol><?php else: ?><p>No qualifications have been published yet.</p><?php endif; ?></section>
                <section id="profile-panel-publications" role="tabpanel" aria-labelledby="profile-tab-publications" data-profile-panel="publications" hidden><p class="eyebrow">Research output</p><h2>Selected publications</h2><?php if ($publications !== []): ?><div class="staff-profile-output-list"><?php foreach ($publications as $publication): ?><article><p><?= View::escape($publication['type_name']) ?><?= $publication['publication_year'] ? ' · ' . (int) $publication['publication_year'] : '' ?></p><h3><a href="<?= View::escape($baseUrl) ?>research/publications/<?= View::escape($publication['slug']) ?>"><?= View::escape($publication['title']) ?></a></h3><?php if (!empty($publication['journal_name'])): ?><span><?= View::escape($publication['journal_name']) ?></span><?php endif; ?></article><?php endforeach; ?></div><?php else: ?><p>No selected publications have been linked yet.</p><?php endif; ?></section>
                <section id="profile-panel-projects" role="tabpanel" aria-labelledby="profile-tab-projects" data-profile-panel="projects" hidden><p class="eyebrow">Research and innovation</p><h2>Projects</h2><?php if ($projects !== []): ?><div class="staff-profile-output-list"><?php foreach ($projects as $project): ?><article><p><?= View::escape(ucfirst((string) $project['project_status'])) ?> project</p><h3><a href="<?= View::escape($baseUrl) ?>research/projects/<?= View::escape($project['slug']) ?>"><?= View::escape($project['title']) ?></a></h3><span><?= View::escape($project['role_title'] ?: ucwords(str_replace('_', ' ', $project['project_role']))) ?></span></article><?php endforeach; ?></div><?php else: ?><p>No projects have been linked yet.</p><?php endif; ?></section>
                <section id="profile-panel-supervision" role="tabpanel" aria-labelledby="profile-tab-supervision" data-profile-panel="supervision" hidden><p class="eyebrow">Graduate research</p><h2>Supervision</h2><p class="staff-profile-availability <?= (int) ($profile['supervision_available'] ?? 0) === 1 ? 'is-available' : '' ?>"><?= (int) ($profile['supervision_available'] ?? 0) === 1 ? 'Currently available for supervision' : 'Supervision availability is not currently advertised' ?></p><?php if (trim((string) ($profile['supervision_interests'] ?? '')) !== ''): ?><div class="prose staff-profile-prose"><?= View::richText($profile['supervision_interests']) ?></div><?php else: ?><p>Supervision interests have not been published yet.</p><?php endif; ?></section>
                <section id="profile-panel-more" role="tabpanel" aria-labelledby="profile-tab-more" data-profile-panel="more" hidden><p class="eyebrow">Additional profile information</p><h2>Teaching and research</h2><?php if (trim((string) ($profile['research_summary'] ?? '')) !== ''): ?><div class="staff-profile-panel-section"><h3>Research interests</h3><div class="prose staff-profile-prose"><?= View::richText($profile['research_summary']) ?></div></div><?php endif; ?><?php if (trim((string) ($profile['teaching_summary'] ?? '')) !== ''): ?><div class="staff-profile-panel-section"><h3>Teaching areas</h3><div class="prose staff-profile-prose"><?= View::richText($profile['teaching_summary']) ?></div></div><?php endif; ?><?php if ($researchUnits !== []): ?><div class="staff-profile-panel-section"><h3>Research groups and units</h3><ul class="staff-profile-related-links"><?php foreach ($researchUnits as $unitRecord): ?><li><a href="<?= View::escape($baseUrl) ?>research/<?= View::escape($unitRecord['slug']) ?>"><?= View::escape($unitRecord['name']) ?></a><span><?= View::escape($unitRecord['role_title'] ?: ucwords(str_replace('_', ' ', $unitRecord['membership_role']))) ?></span></li><?php endforeach; ?></ul></div><?php endif; ?><?php if (trim((string) ($profile['research_summary'] ?? '')) === '' && trim((string) ($profile['teaching_summary'] ?? '')) === '' && $researchUnits === []): ?><p>No additional profile information has been published yet.</p><?php endif; ?></section>
            </div>
        </div>
    </div>
</section>
