<?php declare(strict_types=1);use FastWebsite\Core\View;
$queryForPage = static function (int $page) use ($search, $statusFilter, $typeFilter): string {
    return http_build_query(array_filter(
        ['q' => $search, 'status' => $statusFilter, 'type' => $typeFilter, 'page' => $page],
        static fn (mixed $value): bool => $value !== ''
    ));
};
?>
<section class="admin-page-heading"><div><p class="eyebrow">Phase 7 · Publications</p><h1>Research publications</h1><p>Manage bibliographic records, authors, research links, and publication.</p></div><?php if($canCreate):?><a class="button button-primary" href="<?=View::escape($baseUrl)?>admin/research/publications/create">Create publication</a><?php endif;?></section><?php if(is_string($success)&&$success!==''):?><div class="success-alert"><?=View::escape($success)?></div><?php endif;?><form class="filter-bar" method="get" action="<?=View::escape($baseUrl)?>admin/research/publications"><div><label for="publication-search">Search publications</label><input id="publication-search" name="q" type="search" value="<?=View::escape($search)?>" placeholder="Title, DOI, journal"></div><div><label for="publication-type">Type</label><select id="publication-type" name="type"><option value="">All types</option><?php foreach($types as$type):?><option value="<?=View::escape($type['code'])?>"<?=$typeFilter===$type['code']?' selected':''?>><?=View::escape($type['name'])?></option><?php endforeach;?></select></div><div><label for="publication-status">Status</label><select id="publication-status" name="status"><option value="">All statuses</option><?php foreach($statuses as$status):?><option value="<?=$status?>"<?=$statusFilter===$status?' selected':''?>><?=ucfirst(str_replace('_',' ',$status))?></option><?php endforeach;?></select></div><button class="button button-primary" type="submit">Apply filters</button></form><section class="admin-panel"><div class="panel-heading"><h2><?=number_format($result['total'])?> publication<?=$result['total']===1?'':'s'?></h2></div><?php if($result['items']===[]):?><div class="admin-empty">No publications match the current filters.</div><?php else:?><div class="table-scroll"><table class="admin-table"><thead><tr><th>Publication</th><th>Type</th><th>Year</th><th>Status</th><th></th></tr></thead><tbody><?php foreach($result['items']as$p):?><tr><th><?=View::escape($p['title'])?><small><?=View::escape($p['journal_name']??'')?></small></th><td><?=View::escape($p['type_name'])?></td><td><?=View::escape((string)($p['publication_year']??'—'))?></td><td><span class="status-badge status-<?=View::escape($p['status'])?>"><?=View::escape(ucfirst(str_replace('_',' ',$p['status'])))?></span></td><td><a class="button button-secondary button-compact" href="<?=View::escape($baseUrl)?>admin/research/publications/<?=(int)$p['id']?>">Open</a></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></section>
<?php if ($result['pages'] > 1): ?>
    <nav class="pagination" aria-label="Publication pages">
        <?php for ($page = 1; $page <= $result['pages']; $page++): ?>
            <a href="<?= View::escape($baseUrl . 'admin/research/publications?' . $queryForPage($page)) ?>" <?= $page === $result['page'] ? 'aria-current="page"' : '' ?>><?= $page ?></a>
        <?php endfor; ?>
    </nav>
<?php endif; ?>
