<?php

declare(strict_types=1);

namespace FastWebsite\Controllers;

use FastWebsite\Core\Controller;use FastWebsite\Core\Csrf;use FastWebsite\Core\HttpException;use FastWebsite\Core\Request;use FastWebsite\Core\Response;use FastWebsite\Core\Session;use FastWebsite\Repositories\AssetRepository;use FastWebsite\Services\AdminPageContext;use FastWebsite\Services\AssetService;use FastWebsite\Services\AuthService;use FastWebsite\Services\DocumentUploadService;use FastWebsite\Services\MediaUploadService;use Throwable;

final class AssetAdminController extends Controller
{
    public function __construct(\FastWebsite\Core\View$view,private readonly AuthService$auth,private readonly AdminPageContext$context,private readonly AssetRepository$r,private readonly AssetService$s,private readonly MediaUploadService$images,private readonly DocumentUploadService$documents,private readonly Csrf$csrf,private readonly Session$session){parent::__construct($view);}public function media(Request$q):Response{$u=$this->user();return$this->admin($q,$u,'admin/assets/media-index',['pageTitle'=>'Media library','items'=>$this->r->media()]);}public function uploadMedia(Request$q):Response{$this->check($q);$u=$this->user();$ajax=$q->input('ajax')==='1';$v=$this->images->validate($q->file('image'),(string)$q->input('alt_text',''));if($v['errors']!==[]){if($ajax)return Response::json(['errors'=>$v['errors']],422);return$this->admin($q,$u,'admin/assets/media-index',['pageTitle'=>'Media library','items'=>$this->r->media(),'errors'=>$v['errors']]);}$stored=$this->images->store($v['upload'],(int)$u['id'],'media');if($ajax)return Response::json(['id'=>$stored['id'],'url'=>$q->baseUrl().ltrim(str_replace('public/','',$stored['public_path']),'/'),'alt'=>$v['upload']['alt_text'],'name'=>$v['upload']['original_name']],201);$this->session->put('_flash_success','Image uploaded and its URL is ready to reuse.');return Response::redirect($q->baseUrl().'admin/media/'.$stored['id'].'/edit');}public function editMedia(Request$q):Response{$u=$this->user();$item=$this->r->findMedia($this->id($q));if($item===null)throw new HttpException(404,'Image not found.');return$this->admin($q,$u,'admin/assets/media-form',['pageTitle'=>'Edit image','item'=>$item]);}public function updateMedia(Request$q):Response{$this->check($q);$id=$this->id($q);if($this->r->findMedia($id)===null)throw new HttpException(404,'Image not found.');$this->r->updateMedia($id,['alt_text'=>$this->null($q->input('alt_text'),255),'caption'=>$this->null($q->input('caption'),20000),'copyright_notice'=>$this->null($q->input('copyright_notice'),255)]);return$this->done($q,'Image details saved.','admin/media');}public function mediaWorkflow(Request$q):Response{$this->check($q);$u=$this->user();$status=$this->s->mediaStatus($this->id($q),(string)$q->input('action',''),(int)$u['id'],$q->ipAddress(),$q->userAgent());return$this->done($q,'Image changed to '.$status.'.','admin/media');}
    public function docs(Request$q):Response{$u=$this->user();return$this->admin($q,$u,'admin/assets/documents-index',['pageTitle'=>'Documents','items'=>$this->r->documents()]);}public function createDoc(Request$q):Response{return$this->docForm($q,$this->user());}public function storeDoc(Request$q):Response{return$this->saveDoc($q,$this->user());}public function editDoc(Request$q):Response{$u=$this->user();$item=$this->r->findDocument($this->id($q));if($item===null)throw new HttpException(404,'Document not found.');return$this->docForm($q,$u,$item,[],$this->id($q));}public function updateDoc(Request$q):Response{return$this->saveDoc($q,$this->user(),$this->id($q));}public function docWorkflow(Request$q):Response{$this->check($q);$u=$this->user();$status=$this->s->documentStatus($this->id($q),(string)$q->input('action',''),(int)$u['id'],$q->ipAddress(),$q->userAgent());return$this->done($q,'Document changed to '.$status.'.','admin/documents');}
    /** @param array<string,mixed>$u */private function saveDoc(Request$q,array$u,?int$id=null):Response{$this->check($q);$values=[];foreach(['document_type_id','title','description','version_label','effective_date','review_date','is_public']as$f)$values[$f]=$q->input($f);$errors=[];$type=$this->number($values['document_type_id']);if(trim((string)$values['title'])==='')$errors[]='Document title is required.';if($type!==null&&!$this->r->relation('document_types',$type))$errors[]='Choose a valid document type.';foreach(['effective_date','review_date']as$f)if(trim((string)$values[$f])!==''&&!preg_match('/^\d{4}-\d{2}-\d{2}$/',(string)$values[$f]))$errors[]='Choose valid document dates.';$upload=$this->documents->validate($q->file('document'),$id===null);$errors=[...$errors,...$upload['errors']];if($errors!==[])return$this->docForm($q,$u,$values,$errors,$id);$data=['document_type_id'=>$type,'title'=>mb_substr(trim((string)$values['title']),0,255),'description'=>$this->null($values['description'],20000),'version_label'=>$this->null($values['version_label'],80),'effective_date'=>$this->null($values['effective_date'],10),'review_date'=>$this->null($values['review_date'],10),'is_public'=>(string)$values['is_public']==='1'?1:0,'uploaded_by'=>(int)$u['id']];$old=$id?$this->r->findDocument($id):null;if($upload['upload']===null&&$old!==null)foreach(['original_name','stored_name','file_path','mime_type','file_size']as$f)$data[$f]=$old[$f];$path=null;try{if($upload['upload']!==null){$stored=$this->documents->store($upload['upload']);$path=$stored['absolute_path'];unset($stored['absolute_path']);$data=[...$data,...$stored];}$saved=$this->r->saveDocument($id,$data);if($q->input('submit_action')==='publish')$this->r->documentStatus($saved,'published');}catch(Throwable$e){$this->documents->remove($path);throw$e;}return$this->done($q,$q->input('submit_action')==='publish'?'Document saved and published.':'Document saved.','admin/documents');}
    /** @param array<string,mixed>$u */private function docForm(Request$q,array$u,array$values=[],array$errors=[],?int$id=null):Response{if($values===[])$values=['is_public'=>'1'];return$this->admin($q,$u,'admin/assets/document-form',['pageTitle'=>$id?'Edit document':'Upload document','itemId'=>$id,'values'=>$values,'errors'=>$errors,'types'=>$this->r->types()]);}private function user():array{return$this->auth->user()??throw new HttpException(403,'Authentication required.');}private function id(Request$q):int{$v=(string)$q->route('id','');if(!ctype_digit($v)||(int)$v<1)throw new HttpException(404,'Asset not found.');return(int)$v;}private function check(Request$q):void{if(!$this->csrf->validate($q->input('_token')))throw new HttpException(403,'The secure form session expired.');}private function null(mixed$v,int$m):?string{$v=mb_substr(trim((string)$v),0,$m);return$v===''?null:$v;}private function number(mixed$v):?int{$v=trim((string)$v);return ctype_digit($v)&&(int)$v>0?(int)$v:null;}private function done(Request$q,string$m,string$p):Response{$this->session->put('_flash_success',$m);return Response::redirect($q->baseUrl().$p);}/** @param array<string,mixed>$u */private function admin(Request$q,array$u,string$t,array$d):Response{return$this->view($t,array_merge($this->context->data($q,$u),$d),200,'layouts/admin')->withHeader('Cache-Control','no-store');}
}
