<?php

declare(strict_types=1);

namespace FastWebsite\Controllers;

use FastWebsite\Core\Controller;use FastWebsite\Core\Csrf;use FastWebsite\Core\HttpException;use FastWebsite\Core\Request;use FastWebsite\Core\Response;use FastWebsite\Core\Session;use FastWebsite\Repositories\EngagementRepository;use FastWebsite\Services\AdminPageContext;use FastWebsite\Services\AuthService;use FastWebsite\Services\AuthorizationService;use FastWebsite\Services\EngagementService;use FastWebsite\Services\MediaUploadService;use FastWebsite\Validation\EngagementValidator;use Throwable;

final class EngagementAdminController extends Controller
{
    public function __construct(\FastWebsite\Core\View$view,private readonly AuthService$auth,private readonly AuthorizationService$a,private readonly AdminPageContext$context,private readonly EngagementRepository$r,private readonly EngagementValidator$v,private readonly EngagementService$s,private readonly MediaUploadService$uploads,private readonly Csrf$csrf,private readonly Session$session){parent::__construct($view);}public function index(Request$q):Response{$u=$this->user();return$this->admin($q,$u,'admin/engagement/index',['pageTitle'=>'Engagement','engagementPages'=>$this->r->engagementPages(),'partnerships'=>$this->r->partnerships(),'impacts'=>$this->r->impacts((int)$u['id']),'canCreate'=>$this->a->can((int)$u['id'],'research.create'),'canEdit'=>$this->a->can((int)$u['id'],'research.edit'),'canManagePages'=>$this->a->can((int)$u['id'],'pages.manage'),'canPublish'=>$this->a->can((int)$u['id'],'research.publish')&&$this->a->can((int)$u['id'],'content.approve'),'canManagePartnerships'=>$this->r->global((int)$u['id'])]);}
    public function createPartnership(Request$q):Response{$u=$this->user();return$this->partnershipForm($q,$u);}public function storePartnership(Request$q):Response{return$this->savePartnership($q,$this->user());}public function editPartnership(Request$q):Response{$u=$this->user();$id=$this->id($q);$item=$this->r->findPartnership($id);if($item===null)throw new HttpException(404,'Partnership not found.');return$this->partnershipForm($q,$u,$item,[],$id);}public function updatePartnership(Request$q):Response{return$this->savePartnership($q,$this->user(),$this->id($q));}public function partnershipWorkflow(Request$q):Response{$this->check($q);$u=$this->user();$target=$this->s->partnershipStatus($this->id($q),(string)$q->input('action',''),(int)$u['id'],$q->ipAddress(),$q->userAgent());$this->session->put('_flash_success','Partnership status changed to '.$target.'.');return Response::redirect($q->baseUrl().'admin/engagement');}
    public function createImpact(Request$q):Response{$u=$this->user();return$this->impactForm($q,$u);}public function storeImpact(Request$q):Response{return$this->saveImpact($q,$this->user());}public function editImpact(Request$q):Response{$u=$this->user();$id=$this->id($q);$item=$this->r->findImpact($id,(int)$u['id']);if($item===null)throw new HttpException(404,'Impact story not found.');return$this->impactForm($q,$u,$item,[],$id);}public function updateImpact(Request$q):Response{return$this->saveImpact($q,$this->user(),$this->id($q));}public function impactWorkflow(Request$q):Response{$this->check($q);$u=$this->user();$target=$this->s->impactStatus($this->id($q),(string)$q->input('action',''),(int)$u['id'],$q->ipAddress(),$q->userAgent());$this->session->put('_flash_success','Impact story status changed to '.$target.'.');return Response::redirect($q->baseUrl().'admin/engagement#impact');}
    /** @param array<string,mixed>$u */private function savePartnership(Request$q,array$u,?int$id=null):Response{$this->check($q);$i=[];foreach(['partner_id','faculty_id','title','partnership_type','description','start_date','end_date','reference_number','document_id']as$f)$i[$f]=$q->input($f);$v=$this->v->partnership($i);if($v['errors']!==[])return$this->partnershipForm($q,$u,$i,$v['errors'],$id);$publish=$q->input('submit_action')==='publish';$this->s->savePartnership($id,$v['data'],(int)$u['id'],$publish,$q->ipAddress(),$q->userAgent());$this->session->put('_flash_success',$publish?'Partnership saved and published.':'Partnership saved.');return Response::redirect($q->baseUrl().'admin/engagement');}
    /** @param array<string,mixed>$u @param array<string,mixed>$values @param list<string>$errors */private function partnershipForm(Request$q,array$u,array$values=[],array$errors=[],?int$id=null):Response{if($values===[])$values=['faculty_id'=>(string)($this->r->faculties()[0]['id']??''),'partnership_type'=>'research'];return$this->admin($q,$u,'admin/engagement/partnership-form',['pageTitle'=>$id===null?'Create partnership':'Edit partnership','itemId'=>$id,'values'=>$values,'errors'=>$errors,'partners'=>$this->r->partners(),'faculties'=>$this->r->faculties(),'documents'=>$this->r->documents(),'canPublish'=>$this->a->can((int)$u['id'],'research.publish')&&$this->a->can((int)$u['id'],'content.approve')]);}
    /** @param array<string,mixed>$u */private function saveImpact(Request$q,array$u,?int$id=null):Response{$this->check($q);$i=[];foreach(['department_id','project_id','title','slug','summary','body','beneficiaries','location_text','impact_date','featured_media_id']as$f)$i[$f]=$q->input($f);$v=$this->v->impact($i,(int)$u['id'],$id);$upload=$this->uploads->validate($q->file('featured_image'),(string)$q->input('featured_alt_text',''));$errors=[...$v['errors'],...$upload['errors']];if($errors!==[])return$this->impactForm($q,$u,$i,$errors,$id);$publish=$q->input('submit_action')==='publish';$op=function(array$data)use($id,$u,$publish,$q):int{return$this->s->saveImpact($id,$data,(int)$u['id'],$publish,$q->ipAddress(),$q->userAgent());};$this->withImage($v['data'],$upload['upload'],(int)$u['id'],$op);$this->session->put('_flash_success',$publish?'Impact story saved and published.':'Impact story saved.');return Response::redirect($q->baseUrl().'admin/engagement#impact');}
    /** @param array<string,mixed>$u @param array<string,mixed>$values @param list<string>$errors */private function impactForm(Request$q,array$u,array$values=[],array$errors=[],?int$id=null):Response{if($values===[]){$deps=$this->r->departments((int)$u['id']);$values=['department_id'=>(string)($deps[0]['id']??''),'impact_date'=>date('Y-m-d')];}return$this->admin($q,$u,'admin/engagement/impact-form',['pageTitle'=>$id===null?'Create impact story':'Edit impact story','itemId'=>$id,'values'=>$values,'errors'=>$errors,'departments'=>$this->r->departments((int)$u['id']),'projects'=>$this->r->projects((int)$u['id']),'images'=>$this->r->images(),'canPublish'=>$this->a->can((int)$u['id'],'research.publish')&&$this->a->can((int)$u['id'],'content.approve')]);}
    /** @param array<string,mixed>$u @param array<string,mixed>$d */private function admin(Request$q,array$u,string$t,array$d):Response{return$this->view($t,array_merge($this->context->data($q,$u),$d),200,'layouts/admin')->withHeader('Cache-Control','no-store');}private function user():array{return$this->auth->user()??throw new HttpException(403,'Authentication required.');}private function id(Request$q):int{$v=(string)$q->route('id','');if(!ctype_digit($v)||(int)$v<1)throw new HttpException(404,'Record not found.');return(int)$v;}private function check(Request$q):void{if(!$this->csrf->validate($q->input('_token')))throw new HttpException(403,'The secure form session expired.');}
    /** @param array<string,mixed>$data @param array<string,mixed>|null$upload */private function withImage(array$data,?array$upload,int$u,callable$op):mixed{if($upload===null)return$op($data);$c=$this->r->pdo();$owns=!$c->inTransaction();$path=null;if($owns)$c->beginTransaction();try{$stored=$this->uploads->store($upload,$u,'impact');$path=$stored['absolute_path'];$data['featured_media_id']=$stored['id'];$result=$op($data);if($owns)$c->commit();return$result;}catch(Throwable$e){if($owns&&$c->inTransaction())$c->rollBack();$this->uploads->removeStoredFile($path);throw$e;}}
}
