<?php

declare(strict_types=1);

namespace FastWebsite\Controllers;

use FastWebsite\Core\Controller;use FastWebsite\Core\Csrf;use FastWebsite\Core\HttpException;use FastWebsite\Core\Request;use FastWebsite\Core\Response;use FastWebsite\Core\Session;use FastWebsite\Repositories\InnovationRepository;use FastWebsite\Services\AdminPageContext;use FastWebsite\Services\AuthService;use FastWebsite\Services\AuthorizationService;use FastWebsite\Services\InnovationService;use FastWebsite\Services\MediaUploadService;use FastWebsite\Validation\InnovationValidator;use Throwable;

final class InnovationAdminController extends Controller
{
    public function __construct(\FastWebsite\Core\View$view,private readonly AuthService$auth,private readonly AuthorizationService$authorization,private readonly AdminPageContext$context,private readonly InnovationRepository$repository,private readonly InnovationValidator$validator,private readonly InnovationService$service,private readonly MediaUploadService$uploads,private readonly Csrf$csrf,private readonly Session$session){parent::__construct($view);}
    public function innovations(Request$r):Response{$u=$this->user();return$this->admin($r,$u,'admin/innovations/index',['pageTitle'=>'Innovations','innovations'=>$this->repository->innovations((int)$u['id']),'canCreate'=>$this->authorization->can((int)$u['id'],'research.create'),'canEdit'=>$this->authorization->can((int)$u['id'],'research.edit'),'canPublish'=>$this->authorization->can((int)$u['id'],'research.publish')&&$this->authorization->can((int)$u['id'],'content.approve')]);}
    public function createInnovation(Request$r):Response{$u=$this->user();$this->assert((int)$u['id'],'research.create');return$this->innovationForm($r,$u);}
    public function storeInnovation(Request$r):Response{$u=$this->user();$this->assert((int)$u['id'],'research.create');return$this->saveInnovation($r,$u);}
    public function editInnovation(Request$r):Response{$u=$this->user();$this->assert((int)$u['id'],'research.edit');$id=$this->id($r,'id','Innovation');$item=$this->repository->findInnovation($id,(int)$u['id']);if($item===null)throw new HttpException(404,'Innovation not found.');return$this->innovationForm($r,$u,$item,[],$id);}
    public function updateInnovation(Request$r):Response{$u=$this->user();$this->assert((int)$u['id'],'research.edit');return$this->saveInnovation($r,$u,$this->id($r,'id','Innovation'));}
    public function innovationWorkflow(Request$r):Response{$this->csrf($r);$u=$this->user();$id=$this->id($r,'id','Innovation');$target=$this->service->innovationStatus($id,(string)$r->input('action',''),(int)$u['id'],$r->ipAddress(),$r->userAgent());$this->session->put('_flash_success','Innovation status changed to '.$target.'.');return Response::redirect($r->baseUrl().'admin/innovations');}
    public function facilities(Request$r):Response{$u=$this->user();return$this->admin($r,$u,'admin/facilities/index',['pageTitle'=>'Facilities and equipment','facilities'=>$this->repository->facilities((int)$u['id']),'equipment'=>$this->repository->equipment((int)$u['id']),'canCreate'=>$this->authorization->can((int)$u['id'],'research.create'),'canEdit'=>$this->authorization->can((int)$u['id'],'research.edit')]);}
    public function createFacility(Request$r):Response{$u=$this->user();$this->assert((int)$u['id'],'research.create');return$this->facilityForm($r,$u);}
    public function storeFacility(Request$r):Response{$u=$this->user();$this->assert((int)$u['id'],'research.create');return$this->saveFacility($r,$u);}
    public function editFacility(Request$r):Response{$u=$this->user();$this->assert((int)$u['id'],'research.edit');$id=$this->id($r,'id','Facility');$item=$this->repository->findFacility($id,(int)$u['id']);if($item===null)throw new HttpException(404,'Facility not found.');return$this->facilityForm($r,$u,$item,[],$id);}
    public function updateFacility(Request$r):Response{$u=$this->user();$this->assert((int)$u['id'],'research.edit');return$this->saveFacility($r,$u,$this->id($r,'id','Facility'));}
    public function createEquipment(Request$r):Response{$u=$this->user();$this->assert((int)$u['id'],'research.create');return$this->equipmentForm($r,$u);}
    public function storeEquipment(Request$r):Response{$u=$this->user();$this->assert((int)$u['id'],'research.create');return$this->saveEquipment($r,$u);}
    public function editEquipment(Request$r):Response{$u=$this->user();$this->assert((int)$u['id'],'research.edit');$id=$this->id($r,'id','Equipment');$item=$this->repository->findEquipment($id,(int)$u['id']);if($item===null)throw new HttpException(404,'Equipment not found.');return$this->equipmentForm($r,$u,$item,[],$id);}
    public function updateEquipment(Request$r):Response{$u=$this->user();$this->assert((int)$u['id'],'research.edit');return$this->saveEquipment($r,$u,$this->id($r,'id','Equipment'));}
    /** @param array<string,mixed>$u */private function saveInnovation(Request$r,array$u,?int$id=null):Response{$this->csrf($r);$values=[];foreach(['project_id','lead_department_id','name','slug','innovation_type','description','development_stage','intellectual_property_status','external_url','hero_media_id']as$f)$values[$f]=$r->input($f);$validation=$this->validator->innovation($values,(int)$u['id'],$id);$upload=$this->uploads->validate($r->file('hero_image'),(string)$r->input('hero_alt_text',''));$errors=[...$validation['errors'],...$upload['errors']];if($errors!==[])return$this->innovationForm($r,$u,$values,$errors,$id);$publish=$r->input('submit_action')==='publish';$operation=function(array$data)use($id,$u,$publish,$r):int{return$this->service->saveInnovation($id,$data,(int)$u['id'],$publish,$r->ipAddress(),$r->userAgent());};$saved=$this->withImage($validation['data'],$upload['upload'],(int)$u['id'],$operation);$this->session->put('_flash_success',$publish?'Innovation saved and published.':'Innovation saved.');return Response::redirect($r->baseUrl().'admin/innovations');}
    /** @param array<string,mixed>$u @param array<string,mixed>$v @param list<string>$errors */private function innovationForm(Request$r,array$u,array$v=[],array$errors=[],?int$id=null):Response{if($v===[]){$deps=$this->repository->departments((int)$u['id']);$v=['lead_department_id'=>(string)($deps[0]['id']??''),'innovation_type'=>'prototype'];}return$this->admin($r,$u,'admin/innovations/form',['pageTitle'=>$id===null?'Create innovation':'Edit innovation','itemId'=>$id,'values'=>$v,'errors'=>$errors,'departments'=>$this->repository->departments((int)$u['id']),'projects'=>$this->repository->projects((int)$u['id']),'images'=>$this->repository->activeImages(),'canPublish'=>$this->authorization->can((int)$u['id'],'research.publish')&&$this->authorization->can((int)$u['id'],'content.approve')]);}
    /** @param array<string,mixed>$u */private function saveFacility(Request$r,array$u,?int$id=null):Response{$this->csrf($r);$v=[];foreach(['research_unit_id','name','facility_type','description','location_id','status']as$f)$v[$f]=$r->input($f);$validation=$this->validator->facility($v,(int)$u['id']);if($validation['errors']!==[])return$this->facilityForm($r,$u,$v,$validation['errors'],$id);$this->service->saveFacility($id,$validation['data'],(int)$u['id'],$r->ipAddress(),$r->userAgent());$this->session->put('_flash_success','Facility saved.');return Response::redirect($r->baseUrl().'admin/facilities');}
    /** @param array<string,mixed>$u @param array<string,mixed>$v @param list<string>$errors */private function facilityForm(Request$r,array$u,array$v=[],array$errors=[],?int$id=null):Response{if($v===[]){$units=$this->repository->researchUnits((int)$u['id']);$v=['research_unit_id'=>(string)($units[0]['id']??''),'facility_type'=>'laboratory','status'=>'active'];}return$this->admin($r,$u,'admin/facilities/facility-form',['pageTitle'=>$id===null?'Create facility':'Edit facility','itemId'=>$id,'values'=>$v,'errors'=>$errors,'units'=>$this->repository->researchUnits((int)$u['id']),'locations'=>$this->repository->locations()]);}
    /** @param array<string,mixed>$u */private function saveEquipment(Request$r,array$u,?int$id=null):Response{$this->csrf($r);$v=[];foreach(['research_unit_id','facility_id','name','manufacturer','model','asset_reference','capabilities','availability_status','external_use_allowed','booking_information','status']as$f)$v[$f]=$r->input($f);$validation=$this->validator->equipment($v,(int)$u['id']);if($validation['errors']!==[])return$this->equipmentForm($r,$u,$v,$validation['errors'],$id);$this->service->saveEquipment($id,$validation['data'],(int)$u['id'],$r->ipAddress(),$r->userAgent());$this->session->put('_flash_success','Equipment saved.');return Response::redirect($r->baseUrl().'admin/facilities#equipment');}
    /** @param array<string,mixed>$u @param array<string,mixed>$v @param list<string>$errors */private function equipmentForm(Request$r,array$u,array$v=[],array$errors=[],?int$id=null):Response{if($v===[]){$units=$this->repository->researchUnits((int)$u['id']);$v=['research_unit_id'=>(string)($units[0]['id']??''),'availability_status'=>'available','status'=>'active'];}return$this->admin($r,$u,'admin/facilities/equipment-form',['pageTitle'=>$id===null?'Create equipment':'Edit equipment','itemId'=>$id,'values'=>$v,'errors'=>$errors,'units'=>$this->repository->researchUnits((int)$u['id']),'facilities'=>$this->repository->facilities((int)$u['id'])]);}
    /** @param array<string,mixed>$u @param array<string,mixed>$data */private function admin(Request$r,array$u,string$template,array$data):Response{return$this->view($template,array_merge($this->context->data($r,$u),$data),200,'layouts/admin')->withHeader('Cache-Control','no-store');}private function user():array{return$this->auth->user()??throw new HttpException(403,'Authentication required.');}private function id(Request$r,string$key,string$label):int{$v=(string)$r->route($key,'');if(!ctype_digit($v)||(int)$v<1)throw new HttpException(404,$label.' not found.');return(int)$v;}private function assert(int$u,string$p):void{if(!$this->authorization->can($u,$p))throw new HttpException(403,'This action is not allowed.');}private function csrf(Request$r):void{if(!$this->csrf->validate($r->input('_token')))throw new HttpException(403,'The secure form session expired.');}
    /** @param array<string,mixed>$data @param array<string,mixed>|null$upload */private function withImage(array$data,?array$upload,int$userId,callable$operation):mixed{if($upload===null)return$operation($data);$connection=$this->repository->connection();$owns=!$connection->inTransaction();$path=null;if($owns)$connection->beginTransaction();try{$stored=$this->uploads->store($upload,$userId,'innovations');$path=$stored['absolute_path'];$data['hero_media_id']=$stored['id'];$result=$operation($data);if($owns)$connection->commit();return$result;}catch(Throwable$e){if($owns&&$connection->inTransaction())$connection->rollBack();$this->uploads->removeStoredFile($path);throw$e;}}
}
