<?php

declare(strict_types=1);

namespace FastWebsite\Controllers;

use FastWebsite\Core\Controller;
use FastWebsite\Core\Csrf;
use FastWebsite\Core\HttpException;
use FastWebsite\Core\Request;
use FastWebsite\Core\Response;
use FastWebsite\Core\Session;
use FastWebsite\Repositories\ResearchRepository;
use FastWebsite\Services\AdminPageContext;
use FastWebsite\Services\AuthService;
use FastWebsite\Services\AuthorizationService;
use FastWebsite\Services\MediaUploadService;
use FastWebsite\Services\ResearchService;
use FastWebsite\Validation\ResearchUnitValidator;
use Throwable;

final class ResearchAdminController extends Controller
{
    private const STATUSES=['draft','under_review','approved','published','archived'];
    private const FIELDS=['faculty_id','department_id','unit_type_id','name','acronym','slug','overview','research_focus','capabilities','student_opportunities','industry_services','location_id','hero_media_id','email','phone','website_url','display_order'];
    public function __construct(\FastWebsite\Core\View$view,private readonly AuthService$auth,private readonly AuthorizationService$authorization,private readonly AdminPageContext$context,private readonly ResearchRepository$research,private readonly ResearchUnitValidator$validator,private readonly ResearchService$service,private readonly MediaUploadService$uploads,private readonly Csrf$csrf,private readonly Session$session){parent::__construct($view);}
    public function index(Request$request):Response{$user=$this->user();$search=mb_substr(trim((string)$request->query('q','')),0,100);$status=(string)$request->query('status','');$status=in_array($status,self::STATUSES,true)?$status:'';$page=ctype_digit((string)$request->query('page','1'))?max(1,(int)$request->query('page','1')):1;return$this->adminView($request,$user,'admin/research/index',['pageTitle'=>'Research','result'=>$this->research->paginateAdmin((int)$user['id'],$search,$status,$page),'search'=>$search,'statusFilter'=>$status,'statuses'=>self::STATUSES,'canCreate'=>$this->service->canCreate((int)$user['id'])]);}
    public function show(Request$request):Response{$user=$this->user();$id=$this->id($request);$unit=$this->research->findAdmin($id,(int)$user['id']);if($unit===null)throw new HttpException(404,'Research unit not found.');$canPublish=$this->service->canDirectPublish((int)$user['id'],$id);return$this->adminView($request,$user,'admin/research/show',['pageTitle'=>$unit['name'],'unit'=>$unit,'members'=>$this->research->members($id),'staffOptions'=>$this->research->availableStaff((int)$user['id']),'history'=>$this->research->approvalHistory($id),'actions'=>$this->service->actions((int)$user['id'],$id,(string)$unit['status']),'canEdit'=>($unit['status']==='draft'&&$this->authorization->can((int)$user['id'],'research.edit'))||($unit['status']==='published'&&$canPublish),'canManageMembers'=>$this->authorization->can((int)$user['id'],'research.edit'),'canQuickPublish'=>$unit['status']==='draft'&&trim((string)($unit['overview']??''))!==''&&$canPublish,'needsOverviewToPublish'=>$unit['status']==='draft'&&trim((string)($unit['overview']??''))===''&&$canPublish]);}
    public function create(Request$request):Response{$user=$this->user();$this->assert((int)$user['id'],'research.create');return$this->form($request,$user);}
    public function store(Request$request):Response{$user=$this->user();$this->assert((int)$user['id'],'research.create');return$this->save($request,$user);}
    public function edit(Request$request):Response{$user=$this->user();$this->assert((int)$user['id'],'research.edit');$id=$this->id($request);$unit=$this->research->findAdmin($id,(int)$user['id']);if($unit===null)throw new HttpException(404,'Research unit not found.');if($unit['status']!=='draft'&&!($unit['status']==='published'&&$this->service->canDirectPublish((int)$user['id'],$id)))throw new HttpException(409,'This research unit must be draft or published with publishing access before editing.');return$this->form($request,$user,$unit,[],$id,'',(string)$unit['status']);}
    public function update(Request$request):Response{$user=$this->user();$this->assert((int)$user['id'],'research.edit');return$this->save($request,$user,$this->id($request));}
    public function workflow(Request$request):Response{$user=$this->user();$id=$this->id($request);$this->csrf($request);$action=mb_substr(trim((string)$request->input('action','')),0,40);$comment=mb_substr(trim((string)$request->input('comment','')),0,2000);if($action==='publish_now'){$this->service->publishDraft($id,(int)$user['id'],$comment!==''?$comment:'Published directly.',$request->ipAddress(),$request->userAgent());$this->session->put('_flash_success','Research unit published successfully.');}else{$target=$this->service->transition($id,$action,(int)$user['id'],$comment,$request->ipAddress(),$request->userAgent());$this->session->put('_flash_success','Research unit status changed to '.str_replace('_',' ',$target).'.');}return Response::redirect($request->baseUrl().'admin/research/'.$id);}
    public function addMember(Request$request):Response{$this->csrf($request);$user=$this->user();$id=$this->id($request);$staffId=(int)$request->input('staff_id','0');$order=(int)$request->input('display_order','0');$this->service->addMember($id,$staffId,(string)$request->input('membership_role','researcher'),trim((string)$request->input('role_title','')),trim((string)$request->input('start_date','')),$order,(int)$user['id'],$request->ipAddress(),$request->userAgent());$this->session->put('_flash_success','Research unit member added.');return Response::redirect($request->baseUrl().'admin/research/'.$id.'#members');}
    public function removeMember(Request$request):Response{$this->csrf($request);$user=$this->user();$id=$this->id($request);$member=(string)$request->route('memberId','');if(!ctype_digit($member)||(int)$member<1)throw new HttpException(404,'Research unit member not found.');$this->service->removeMember($id,(int)$member,(int)$user['id'],$request->ipAddress(),$request->userAgent());$this->session->put('_flash_success','Research unit member removed.');return Response::redirect($request->baseUrl().'admin/research/'.$id.'#members');}
    /** @param array<string,mixed> $user */ private function save(Request$request,array$user,?int$id=null):Response{$this->csrf($request);$status='draft';if($id!==null){$existing=$this->research->findAdmin($id,(int)$user['id']);if($existing===null)throw new HttpException(404,'Research unit not found.');$status=(string)$existing['status'];}$values=[];foreach(self::FIELDS as$field)$values[$field]=$request->input($field);$validation=$this->validator->validate($values,$id);$upload=$this->uploads->validate($request->file('hero_image'),(string)$request->input('hero_alt_text',''));$errors=[...$validation['errors'],...$upload['errors']];$note=mb_substr(trim((string)$request->input('revision_note','')),0,2000);if($errors!==[])return$this->form($request,$user,$values,$errors,$id,$note,$status);$operation=function(array$data)use($id,$user,$request,$note,$status):int{if($id===null)return$request->input('submit_action')==='publish'?$this->service->createAndPublish($data,(int)$user['id'],$request->ipAddress(),$request->userAgent()):$this->service->create($data,(int)$user['id'],$request->ipAddress(),$request->userAgent());if($status==='published')$this->service->updatePublished($id,$data,(int)$user['id'],$note,$request->ipAddress(),$request->userAgent());elseif($request->input('submit_action')==='publish')$this->service->updateAndPublish($id,$data,(int)$user['id'],$note,$request->ipAddress(),$request->userAgent());else$this->service->update($id,$data,(int)$user['id'],$note,$request->ipAddress(),$request->userAgent());return$id;};$saved=$this->withImage($validation['data'],$upload['upload'],(int)$user['id'],$operation);$message=$id===null?($request->input('submit_action')==='publish'?'Research unit created and published.':'Research unit created as a draft.'):($status==='published'?'Published research unit updated.':($request->input('submit_action')==='publish'?'Research unit saved and published.':'Research unit updated.'));$this->session->put('_flash_success',$message);return Response::redirect($request->baseUrl().'admin/research/'.$saved);}
    /** @param array<string,mixed> $user @param array<string,mixed> $values @param list<string> $errors */ private function form(Request$request,array$user,array$values=[],array$errors=[],?int$id=null,string$note='',string$status='draft'):Response{if($values===[]){$departments=$this->research->departments((int)$user['id']);$values=['faculty_id'=>(string)($departments[0]['faculty_id']??($this->research->faculties()[0]['id']??'')),'department_id'=>(string)($departments[0]['id']??''),'unit_type_id'=>(string)($this->research->types()[0]['id']??''),'display_order'=>'0'];}return$this->adminView($request,$user,'admin/research/form',['pageTitle'=>$id===null?'Create research unit':'Edit research unit','unitId'=>$id,'values'=>$values,'errors'=>$errors,'faculties'=>$this->research->faculties(),'departments'=>$this->research->departments((int)$user['id']),'types'=>$this->research->types(),'locations'=>$this->research->locations(),'images'=>$this->research->activeImages(),'revisionNote'=>$note,'currentStatus'=>$status,'canPublishDirectly'=>$id!==null?$this->service->canDirectPublish((int)$user['id'],$id):$this->authorization->can((int)$user['id'],'research.publish')&&$this->authorization->can((int)$user['id'],'content.approve')]);}
    /** @param array<string,mixed> $user @param array<string,mixed> $data */ private function adminView(Request$request,array$user,string$template,array$data):Response{return$this->view($template,array_merge($this->context->data($request,$user),$data),200,'layouts/admin')->withHeader('Cache-Control','no-store');}
    /** @return array<string,mixed> */ private function user():array{return$this->auth->user()??throw new HttpException(403,'Authentication required.');}
    private function id(Request$request):int{$v=(string)$request->route('id','');if(!ctype_digit($v)||(int)$v<1)throw new HttpException(404,'Research unit not found.');return(int)$v;}
    private function assert(int$userId,string$permission):void{if(!$this->authorization->can($userId,$permission))throw new HttpException(403,'This research action is not allowed.');}
    private function csrf(Request$request):void{if(!$this->csrf->validate($request->input('_token')))throw new HttpException(403,'The secure form session expired.');}
    /** @param array<string,mixed> $data @param array<string,mixed>|null $upload */ private function withImage(array$data,?array$upload,int$userId,callable$operation):mixed{if($upload===null)return$operation($data);$connection=$this->research->connection();$owns=!$connection->inTransaction();$path=null;if($owns)$connection->beginTransaction();try{$stored=$this->uploads->store($upload,$userId,'research');$path=$stored['absolute_path'];$data['hero_media_id']=$stored['id'];$result=$operation($data);if($owns)$connection->commit();return$result;}catch(Throwable$e){if($owns&&$connection->inTransaction())$connection->rollBack();$this->uploads->removeStoredFile($path);throw$e;}}
}
