<?php

declare(strict_types=1);

namespace FastWebsite\Controllers;

use FastWebsite\Core\Controller;use FastWebsite\Core\Csrf;use FastWebsite\Core\HttpException;use FastWebsite\Core\Request;use FastWebsite\Core\Response;use FastWebsite\Core\Session;use FastWebsite\Repositories\SiteContentRepository;use FastWebsite\Services\AdminPageContext;use FastWebsite\Services\AuthService;use FastWebsite\Services\AuthorizationService;use FastWebsite\Services\MediaUploadService;use FastWebsite\Services\SiteContentService;use FastWebsite\Validation\SiteContentValidator;use Throwable;

final class SiteContentAdminController extends Controller
{
    public function __construct(\FastWebsite\Core\View$view,private readonly AuthService$auth,private readonly AuthorizationService$a,private readonly AdminPageContext$context,private readonly SiteContentRepository$r,private readonly SiteContentValidator$v,private readonly SiteContentService$s,private readonly MediaUploadService$uploads,private readonly Csrf$csrf,private readonly Session$session){parent::__construct($view);}
    public function news(Request$q):Response{$u=$this->user();return$this->admin($q,$u,'admin/content/news-index',['pageTitle'=>'News','items'=>$this->r->news((int)$u['id']),'canCreate'=>$this->a->can((int)$u['id'],'news.create'),'canEdit'=>$this->a->can((int)$u['id'],'news.edit'),'canPublish'=>$this->canNewsPublish((int)$u['id'])]);}
    public function createNews(Request$q):Response{return$this->newsForm($q,$this->user());}public function storeNews(Request$q):Response{return$this->saveNews($q,$this->user());}
    public function editNews(Request$q):Response{$u=$this->user();$id=$this->id($q);$item=$this->r->findNews($id,(int)$u['id']);if($item===null)throw new HttpException(404,'News item not found.');return$this->newsForm($q,$u,$item,[],$id);}public function updateNews(Request$q):Response{return$this->saveNews($q,$this->user(),$this->id($q));}public function newsWorkflow(Request$q):Response{$this->check($q);$u=$this->user();$target=$this->s->newsStatus($this->id($q),(string)$q->input('action',''),(int)$u['id'],$q->ipAddress(),$q->userAgent());return$this->done($q,'News item changed to '.$target.'.','admin/news');}
    public function events(Request$q):Response{$u=$this->user();return$this->admin($q,$u,'admin/content/events-index',['pageTitle'=>'Events','items'=>$this->r->events((int)$u['id'])]);}public function createEvent(Request$q):Response{return$this->eventForm($q,$this->user());}public function storeEvent(Request$q):Response{return$this->saveEvent($q,$this->user());}public function editEvent(Request$q):Response{$u=$this->user();$id=$this->id($q);$item=$this->r->findEvent($id,(int)$u['id']);if($item===null)throw new HttpException(404,'Event not found.');return$this->eventForm($q,$u,$item,[],$id);}public function updateEvent(Request$q):Response{return$this->saveEvent($q,$this->user(),$this->id($q));}public function eventWorkflow(Request$q):Response{$this->check($q);$u=$this->user();$target=$this->s->eventStatus($this->id($q),(string)$q->input('action',''),(int)$u['id'],$q->ipAddress(),$q->userAgent());return$this->done($q,'Event changed to '.$target.'.','admin/events');}
    public function pages(Request$q):Response{$u=$this->user();return$this->admin($q,$u,'admin/content/pages-index',['pageTitle'=>'Pages and announcements','pages'=>$this->r->pages(),'announcements'=>$this->r->announcements()]);}public function createPage(Request$q):Response{return$this->pageForm($q,$this->user());}public function storePage(Request$q):Response{return$this->savePage($q,$this->user());}public function editPage(Request$q):Response{$u=$this->user();$id=$this->id($q);$item=$this->r->findPage($id);if($item===null)throw new HttpException(404,'Page not found.');return$this->pageForm($q,$u,$item,[],$id);}public function updatePage(Request$q):Response{return$this->savePage($q,$this->user(),$this->id($q));}public function pageWorkflow(Request$q):Response{$this->check($q);$u=$this->user();$target=$this->s->pageStatus($this->id($q),(string)$q->input('action',''),(int)$u['id'],$q->ipAddress(),$q->userAgent());return$this->done($q,'Page changed to '.$target.'.','admin/pages');}
    public function addSection(Request$q):Response{$this->check($q);$u=$this->user();$page=$this->id($q);if($this->r->findPage($page)===null)throw new HttpException(404,'Page not found.');$input=$this->inputs($q,['section_type','heading','subheading','body','media_id','button_label','button_url','display_order','is_visible']);$v=$this->v->section($input);if($v['errors']!==[]){$this->session->put('_flash_success','Section was not added: '.implode(' ',$v['errors']));return Response::redirect($q->baseUrl().'admin/pages/'.$page.'/edit#sections');}$this->r->addSection($page,$v['data']);return$this->done($q,'Page section added.','admin/pages/'.$page.'/edit#sections');}public function removeSection(Request$q):Response{$this->check($q);$page=$this->id($q);$section=$this->id($q,'sectionId');if(!$this->r->removeSection($page,$section))throw new HttpException(404,'Section not found.');return$this->done($q,'Page section removed.','admin/pages/'.$page.'/edit#sections');}
    public function createAnnouncement(Request$q):Response{return$this->announcementForm($q,$this->user());}public function storeAnnouncement(Request$q):Response{return$this->saveAnnouncement($q,$this->user());}public function editAnnouncement(Request$q):Response{$u=$this->user();$id=$this->id($q);$item=$this->r->findAnnouncement($id);if($item===null)throw new HttpException(404,'Announcement not found.');return$this->announcementForm($q,$u,$item,[],$id);}public function updateAnnouncement(Request$q):Response{return$this->saveAnnouncement($q,$this->user(),$this->id($q));}public function announcementWorkflow(Request$q):Response{$this->check($q);$u=$this->user();$target=$this->s->announcementStatus($this->id($q),(string)$q->input('action',''),(int)$u['id'],$q->ipAddress(),$q->userAgent());return$this->done($q,'Announcement changed to '.$target.'.','admin/pages#announcements');}
    /** @param array<string,mixed>$u */private function saveNews(Request$q,array$u,?int$id=null):Response{$this->check($q);$values=$this->inputs($q,['category_id','department_id','title','slug','summary','body','featured_media_id','article_date','is_featured','allow_sharing','meta_title','meta_description']);$v=$this->v->news($values,(int)$u['id'],$id);$up=$this->uploads->validate($q->file('featured_image'),(string)$q->input('image_alt_text',''));$errors=[...$v['errors'],...$up['errors']];if($errors!==[])return$this->newsForm($q,$u,$values,$errors,$id);$publish=$q->input('submit_action')==='publish';$this->withImage($v['data'],$up['upload'],(int)$u['id'],'news',fn(array$d):int=>$this->s->saveNews($id,$d,$v['department_id'],(int)$u['id'],$publish,$q->ipAddress(),$q->userAgent()));return$this->done($q,$publish?'News saved and published.':'News saved.','admin/news');}
    /** @param array<string,mixed>$u */private function newsForm(Request$q,array$u,array$values=[],array$errors=[],?int$id=null):Response{if($values===[]){$d=$this->r->departments((int)$u['id']);$values=['article_date'=>date('Y-m-d'),'allow_sharing'=>'1','department_id'=>(string)($d[0]['id']??'')];}return$this->admin($q,$u,'admin/content/news-form',['pageTitle'=>$id?'Edit news':'Create news','itemId'=>$id,'values'=>$values,'errors'=>$errors,'categories'=>$this->r->newsCategories(),'departments'=>$this->r->departments((int)$u['id']),'images'=>$this->r->images(),'canPublish'=>$this->canNewsPublish((int)$u['id'])]);}
    /** @param array<string,mixed>$u */private function saveEvent(Request$q,array$u,?int$id=null):Response{$this->check($q);$values=$this->inputs($q,['category_id','department_id','title','slug','summary','description','starts_at','ends_at','venue_name','location_id','contact_staff_id','contact_name','contact_email','registration_url','registration_deadline','featured_media_id','event_status']);$v=$this->v->event($values,(int)$u['id'],$id);$up=$this->uploads->validate($q->file('featured_image'),(string)$q->input('image_alt_text',''));$errors=[...$v['errors'],...$up['errors']];if($errors!==[])return$this->eventForm($q,$u,$values,$errors,$id);$publish=$q->input('submit_action')==='publish';$this->withImage($v['data'],$up['upload'],(int)$u['id'],'events',fn(array$d):int=>$this->s->saveEvent($id,$d,$v['department_id'],(int)$u['id'],$publish,$q->ipAddress(),$q->userAgent()));return$this->done($q,$publish?'Event saved and published.':'Event saved.','admin/events');}
    /** @param array<string,mixed>$u */private function eventForm(Request$q,array$u,array$values=[],array$errors=[],?int$id=null):Response{if($values===[]){$d=$this->r->departments((int)$u['id']);$values=['event_status'=>'scheduled','department_id'=>(string)($d[0]['id']??'')];}return$this->admin($q,$u,'admin/content/event-form',['pageTitle'=>$id?'Edit event':'Create event','itemId'=>$id,'values'=>$values,'errors'=>$errors,'categories'=>$this->r->eventCategories(),'departments'=>$this->r->departments((int)$u['id']),'images'=>$this->r->images(),'staff'=>$this->r->staff(),'locations'=>$this->r->locations()]);}
    /** @param array<string,mixed>$u */private function savePage(Request$q,array$u,?int$id=null):Response{$this->check($q);$values=$this->inputs($q,['parent_page_id','title','slug','page_template','meta_title','meta_description','display_order','show_in_navigation']);$v=$this->v->page($values,$id);if($v['errors']!==[])return$this->pageForm($q,$u,$values,$v['errors'],$id);$publish=$q->input('submit_action')==='publish';$saved=$this->s->savePage($id,$v['data'],(int)$u['id'],$publish,$q->ipAddress(),$q->userAgent());return$this->done($q,$publish?'Page saved and published.':'Page saved.','admin/pages/'.$saved.'/edit');}
    /** @param array<string,mixed>$u */private function pageForm(Request$q,array$u,array$values=[],array$errors=[],?int$id=null):Response{return$this->admin($q,$u,'admin/content/page-form',['pageTitle'=>$id?'Edit page':'Create page','itemId'=>$id,'values'=>$values,'errors'=>$errors,'pages'=>$this->r->pages(),'sections'=>$id?$this->r->sections($id):[],'images'=>$this->r->images()]);}
    /** @param array<string,mixed>$u */private function saveAnnouncement(Request$q,array$u,?int$id=null):Response{$this->check($q);$values=$this->inputs($q,['title','summary','announcement_type','link_url','starts_at','ends_at','is_pinned']);$v=$this->v->announcement($values);if($v['errors']!==[])return$this->announcementForm($q,$u,$values,$v['errors'],$id);$publish=$q->input('submit_action')==='publish';$this->s->saveAnnouncement($id,$v['data'],(int)$u['id'],$publish,$q->ipAddress(),$q->userAgent());return$this->done($q,$publish?'Announcement saved and published.':'Announcement saved.','admin/pages#announcements');}
    /** @param array<string,mixed>$u */private function announcementForm(Request$q,array$u,array$values=[],array$errors=[],?int$id=null):Response{if($values===[])$values=['announcement_type'=>'general'];return$this->admin($q,$u,'admin/content/announcement-form',['pageTitle'=>$id?'Edit announcement':'Create announcement','itemId'=>$id,'values'=>$values,'errors'=>$errors]);}
    /** @param list<string>$fields @return array<string,mixed> */private function inputs(Request$q,array$fields):array{$out=[];foreach($fields as$f)$out[$f]=$q->input($f);return$out;}private function done(Request$q,string$message,string$path):Response{$this->session->put('_flash_success',$message);return Response::redirect($q->baseUrl().$path);}private function user():array{return$this->auth->user()??throw new HttpException(403,'Authentication required.');}private function id(Request$q,string$key='id'):int{$v=(string)$q->route($key,'');if(!ctype_digit($v)||(int)$v<1)throw new HttpException(404,'Content not found.');return(int)$v;}private function check(Request$q):void{if(!$this->csrf->validate($q->input('_token')))throw new HttpException(403,'The secure form session expired.');}private function canNewsPublish(int$u):bool{return$this->a->can($u,'news.publish')&&$this->a->can($u,'content.approve');}/** @param array<string,mixed>$u */private function admin(Request$q,array$u,string$template,array$data):Response{return$this->view($template,array_merge($this->context->data($q,$u),$data),200,'layouts/admin')->withHeader('Cache-Control','no-store');}
    /** @param array<string,mixed>$data @param array<string,mixed>|null$upload */private function withImage(array$data,?array$upload,int$user,string$collection,callable$operation):mixed{if($upload===null)return$operation($data);$pdo=$this->r->pdo();$owns=!$pdo->inTransaction();$path=null;if($owns)$pdo->beginTransaction();try{$stored=$this->uploads->store($upload,$user,$collection);$path=$stored['absolute_path'];$data['featured_media_id']=$stored['id'];$result=$operation($data);if($owns)$pdo->commit();return$result;}catch(Throwable$e){if($owns&&$pdo->inTransaction())$pdo->rollBack();$this->uploads->removeStoredFile($path);throw$e;}}
}
