<?php

declare(strict_types=1);

namespace FastWebsite\Repositories;

use FastWebsite\Core\Database;use PDO;

final class AssetRepository
{
    public function __construct(private readonly Database$db){}
    /** @return list<array<string,mixed>> */public function media():array{return$this->pdo()->query('SELECT m.*,u.name AS uploader_name FROM media m LEFT JOIN users u ON u.id=m.uploaded_by WHERE m.deleted_at IS NULL ORDER BY m.created_at DESC')->fetchAll();}/** @return array<string,mixed>|null */public function findMedia(int$id):?array{$s=$this->pdo()->prepare('SELECT * FROM media WHERE id=:id AND deleted_at IS NULL LIMIT 1');$s->execute(['id'=>$id]);$r=$s->fetch();return is_array($r)?$r:null;}public function updateMedia(int$id,array$d):void{$s=$this->pdo()->prepare('UPDATE media SET alt_text=:alt_text,caption=:caption,copyright_notice=:copyright_notice WHERE id=:id');$s->execute([...$d,'id'=>$id]);}public function mediaStatus(int$id,string$status):void{$s=$this->pdo()->prepare('UPDATE media SET status=:status WHERE id=:id');$s->execute(['status'=>$status,'id'=>$id]);}
    /** @return list<array<string,mixed>> */public function types():array{return$this->pdo()->query('SELECT * FROM document_types ORDER BY name')->fetchAll();}/** @return list<array<string,mixed>> */public function documents(bool$public=false):array{$w='d.deleted_at IS NULL'.($public?' AND d.status="published" AND d.is_public=1 AND d.published_at IS NOT NULL AND d.published_at<=NOW()':'');return$this->pdo()->query('SELECT d.*,t.name AS type_name,u.name AS uploader_name FROM documents d LEFT JOIN document_types t ON t.id=d.document_type_id LEFT JOIN users u ON u.id=d.uploaded_by WHERE '.$w.' ORDER BY d.effective_date DESC,d.created_at DESC')->fetchAll();}/** @return array<string,mixed>|null */public function findDocument(int$id):?array{$s=$this->pdo()->prepare('SELECT * FROM documents WHERE id=:id AND deleted_at IS NULL LIMIT 1');$s->execute(['id'=>$id]);$r=$s->fetch();return is_array($r)?$r:null;}public function saveDocument(?int$id,array$d):int{if($id===null){$f=array_keys($d);$s=$this->pdo()->prepare('INSERT INTO documents('.implode(',',$f).',status)VALUES('.implode(',',array_map(static fn($x)=>':'.$x,$f)).',"draft")');$s->execute($d);return(int)$this->pdo()->lastInsertId();}$set=array_map(static fn($x)=>$x.'=:'.$x,array_keys($d));$s=$this->pdo()->prepare('UPDATE documents SET '.implode(',',$set).' WHERE id=:id');$s->execute([...$d,'id'=>$id]);return$id;}public function documentStatus(int$id,string$status):void{$pub=$status==='published'?',published_at=NOW()':($status==='draft'?',published_at=NULL':'');$s=$this->pdo()->prepare('UPDATE documents SET status=:status'.$pub.' WHERE id=:id');$s->execute(['status'=>$status,'id'=>$id]);}public function relation(string$table,int$id):bool{if(!in_array($table,['document_types'],true))return false;$s=$this->pdo()->prepare("SELECT 1 FROM $table WHERE id=:id LIMIT 1");$s->execute(['id'=>$id]);return$s->fetchColumn()!==false;}public function pdo():PDO{return$this->db->connection();}
}
