<?php

declare(strict_types=1);

namespace FastWebsite\Repositories;

use FastWebsite\Core\Database;
use FastWebsite\Services\DepartmentScopeService;
use PDO;

final class ProjectRepository
{
    public function __construct(private readonly Database$database,private readonly DepartmentScopeService$scope){}
    /** @return list<array<string,mixed>> */ public function departments(int$userId):array{$where=$this->scope->hasGlobalScope($userId)?'1=1':$this->ids('id',$this->scope->departmentIds($userId));return$this->connection()->query('SELECT id,name FROM departments WHERE deleted_at IS NULL AND '.$where.' ORDER BY name')->fetchAll();}
    /** @return list<array<string,mixed>> */ public function researchUnits(int$userId):array{$where=$this->scopeCondition($userId,'ru');return$this->connection()->query('SELECT ru.id,ru.name,ru.acronym,ru.department_id FROM research_units ru WHERE ru.deleted_at IS NULL AND '.$where.' ORDER BY ru.name')->fetchAll();}
    /** @return list<array<string,mixed>> */ public function availableStaff(int$userId):array{$ids=$this->scope->departmentIds($userId);$condition=$this->scope->hasGlobalScope($userId)?'1=1':($ids===[]?'1=0':'EXISTS(SELECT 1 FROM staff_departments sd WHERE sd.staff_id=s.id AND sd.department_id IN('.implode(',',array_map('intval',$ids)).') AND sd.is_current=1)');return$this->connection()->query('SELECT s.id,s.honorific_title,s.first_name,s.middle_name,s.last_name FROM staff s WHERE s.deleted_at IS NULL AND s.status="published" AND '.$condition.' ORDER BY s.first_name,s.last_name')->fetchAll();}
    /** @return list<array<string,mixed>> */ public function activeImages():array{return$this->connection()->query('SELECT id,original_name,file_path,alt_text FROM media WHERE media_type="image" AND status="active" AND deleted_at IS NULL ORDER BY original_name')->fetchAll();}
    /** @return array{items:list<array<string,mixed>>,total:int,page:int,pages:int} */ public function paginateAdmin(int$userId,string$search,string$status,string$projectStatus,int$page,int$perPage=12):array{$conditions=['p.deleted_at IS NULL',$this->scopeCondition($userId,'p')];$params=[];if($search!==''){$conditions[]='(p.title LIKE :title OR p.short_title LIKE :short OR p.summary LIKE :summary)';$params=['title'=>'%'.$search.'%','short'=>'%'.$search.'%','summary'=>'%'.$search.'%'];}if($status!==''){$conditions[]='p.publication_status=:publication_status';$params['publication_status']=$status;}if($projectStatus!==''){$conditions[]='p.project_status=:project_status';$params['project_status']=$projectStatus;}$where=implode(' AND ',$conditions);$count=$this->connection()->prepare('SELECT COUNT(*) FROM projects p WHERE '.$where);$count->execute($params);$total=(int)$count->fetchColumn();$pages=max(1,(int)ceil($total/$perPage));$page=min(max(1,$page),$pages);$s=$this->connection()->prepare(sprintf('SELECT p.id,p.title,p.short_title,p.slug,p.project_status,p.publication_status,p.updated_at,d.name AS department_name FROM projects p LEFT JOIN departments d ON d.id=p.lead_department_id WHERE %s ORDER BY p.start_date DESC,p.title LIMIT %d OFFSET %d',$where,$perPage,($page-1)*$perPage));$s->execute($params);return['items'=>$s->fetchAll(),'total'=>$total,'page'=>$page,'pages'=>$pages];}
    /** @return array<string,mixed>|null */ public function findAdmin(int$id,int$userId):?array{$s=$this->connection()->prepare('SELECT p.*,d.name AS department_name,m.file_path AS hero_path,m.alt_text AS hero_alt_text FROM projects p LEFT JOIN departments d ON d.id=p.lead_department_id LEFT JOIN media m ON m.id=p.hero_media_id AND m.status="active" AND m.deleted_at IS NULL WHERE p.id=:id AND p.deleted_at IS NULL AND '.$this->scopeCondition($userId,'p').' LIMIT 1');$s->execute(['id'=>$id]);$r=$s->fetch();return is_array($r)?$r:null;}
    /** @return array<string,mixed>|null */ public function findForUpdate(int$id):?array{$s=$this->connection()->prepare('SELECT * FROM projects WHERE id=:id AND deleted_at IS NULL FOR UPDATE');$s->execute(['id'=>$id]);$r=$s->fetch();return is_array($r)?$r:null;}
    /** @return array<string,mixed>|null */ public function findPublishedBySlug(string$slug):?array{$s=$this->connection()->prepare('SELECT p.*,d.name AS department_name,d.slug AS department_slug,m.file_path AS hero_path,m.alt_text AS hero_alt_text FROM projects p LEFT JOIN departments d ON d.id=p.lead_department_id LEFT JOIN media m ON m.id=p.hero_media_id AND m.status="active" AND m.deleted_at IS NULL WHERE p.slug=:slug AND p.publication_status="published" AND p.published_at IS NOT NULL AND p.published_at<=NOW() AND p.deleted_at IS NULL LIMIT 1');$s->execute(['slug'=>$slug]);$r=$s->fetch();return is_array($r)?$r:null;}
    /** @return array{items:list<array<string,mixed>>,total:int,page:int,pages:int} */ public function paginatePublished(string$search,string$projectStatus,int$page,int$perPage=12):array{$conditions=['p.publication_status="published"','p.published_at IS NOT NULL','p.published_at<=NOW()','p.deleted_at IS NULL'];$params=[];if($search!==''){$conditions[]='(p.title LIKE :title OR p.short_title LIKE :short OR p.summary LIKE :summary)';$params=['title'=>'%'.$search.'%','short'=>'%'.$search.'%','summary'=>'%'.$search.'%'];}if($projectStatus!==''){$conditions[]='p.project_status=:project_status';$params['project_status']=$projectStatus;}$where=implode(' AND ',$conditions);$count=$this->connection()->prepare('SELECT COUNT(*) FROM projects p WHERE '.$where);$count->execute($params);$total=(int)$count->fetchColumn();$pages=max(1,(int)ceil($total/$perPage));$page=min(max(1,$page),$pages);$s=$this->connection()->prepare(sprintf('SELECT p.id,p.title,p.short_title,p.slug,p.summary,p.project_status,p.start_date,p.end_date,d.name AS department_name,m.file_path AS hero_path,m.alt_text AS hero_alt_text FROM projects p LEFT JOIN departments d ON d.id=p.lead_department_id LEFT JOIN media m ON m.id=p.hero_media_id AND m.status="active" AND m.deleted_at IS NULL WHERE %s ORDER BY FIELD(p.project_status,"ongoing","planned","completed","suspended","cancelled"),p.start_date DESC,p.title LIMIT %d OFFSET %d',$where,$perPage,($page-1)*$perPage));$s->execute($params);return['items'=>$s->fetchAll(),'total'=>$total,'page'=>$page,'pages'=>$pages];}
    /** @return list<array<string,mixed>> */ public function linkedUnits(int$projectId,bool$publishedOnly=false):array{$extra=$publishedOnly?' AND ru.status="published" AND ru.published_at IS NOT NULL AND ru.published_at<=NOW()':'';$s=$this->connection()->prepare('SELECT ru.id,ru.name,ru.acronym,ru.slug,pru.is_lead_unit FROM project_research_units pru INNER JOIN research_units ru ON ru.id=pru.research_unit_id AND ru.deleted_at IS NULL'.$extra.' WHERE pru.project_id=:id ORDER BY pru.is_lead_unit DESC,ru.name');$s->execute(['id'=>$projectId]);return$s->fetchAll();}
    /** @return list<array<string,mixed>> */ public function members(int$projectId,bool$publishedOnly=false):array{$extra=$publishedOnly?' AND (pm.staff_id IS NULL OR (s.status="published" AND s.published_at IS NOT NULL AND s.published_at<=NOW()))':'';$s=$this->connection()->prepare('SELECT pm.*,s.honorific_title,s.first_name,s.middle_name,s.last_name,s.slug AS staff_slug,s.short_biography,m.file_path AS profile_path,m.alt_text AS profile_alt_text FROM project_members pm LEFT JOIN staff s ON s.id=pm.staff_id AND s.deleted_at IS NULL LEFT JOIN media m ON m.id=s.profile_media_id AND m.status="active" AND m.deleted_at IS NULL WHERE pm.project_id=:id'.$extra.' ORDER BY FIELD(pm.project_role,"principal_investigator","co_investigator","project_manager","researcher","technical_staff","student","advisor","collaborator","other"),pm.display_order,pm.id');$s->execute(['id'=>$projectId]);return$s->fetchAll();}
    /** @return list<array<string,mixed>> */ public function milestones(int$projectId):array{$s=$this->connection()->prepare('SELECT pm.*,s.honorific_title,s.first_name,s.last_name,s.slug AS staff_slug FROM project_milestones pm LEFT JOIN staff s ON s.id=pm.lead_staff_id AND s.deleted_at IS NULL WHERE pm.project_id=:id ORDER BY pm.sequence_number,pm.id');$s->execute(['id'=>$projectId]);return$s->fetchAll();}
    /** @return array<string,mixed>|null */ public function findMilestone(int$projectId,int$milestoneId):?array{$s=$this->connection()->prepare('SELECT * FROM project_milestones WHERE id=:id AND project_id=:project');$s->execute(['id'=>$milestoneId,'project'=>$projectId]);$r=$s->fetch();return is_array($r)?$r:null;}
    public function nextMilestoneSequence(int$projectId):int{$s=$this->connection()->prepare('SELECT COALESCE(MAX(sequence_number),0)+1 FROM project_milestones WHERE project_id=:id');$s->execute(['id'=>$projectId]);return(int)$s->fetchColumn();}
    public function createMilestone(int$projectId,int$sequence,string$title,?string$expectedOutput,?string$timeline,string$targetLevel,?string$leadName,?int$leadStaffId,?string$studentNames,string$status):int{$s=$this->connection()->prepare('INSERT INTO project_milestones(project_id,sequence_number,title,expected_output,timeline_text,target_level,lead_name_text,lead_staff_id,student_names_text,status)VALUES(:project,:seq,:title,:output,:timeline,:level,:lead_name,:lead_staff,:students,:status)');$s->execute(['project'=>$projectId,'seq'=>$sequence,'title'=>$title,'output'=>$expectedOutput,'timeline'=>$timeline,'level'=>$targetLevel,'lead_name'=>$leadName,'lead_staff'=>$leadStaffId,'students'=>$studentNames,'status'=>$status]);return(int)$this->connection()->lastInsertId();}
    public function updateMilestone(int$projectId,int$milestoneId,int$sequence,string$title,?string$expectedOutput,?string$timeline,string$targetLevel,?string$leadName,?int$leadStaffId,?string$studentNames,string$status):bool{$s=$this->connection()->prepare('UPDATE project_milestones SET sequence_number=:seq,title=:title,expected_output=:output,timeline_text=:timeline,target_level=:level,lead_name_text=:lead_name,lead_staff_id=:lead_staff,student_names_text=:students,status=:status WHERE id=:id AND project_id=:project');$s->execute(['seq'=>$sequence,'title'=>$title,'output'=>$expectedOutput,'timeline'=>$timeline,'level'=>$targetLevel,'lead_name'=>$leadName,'lead_staff'=>$leadStaffId,'students'=>$studentNames,'status'=>$status,'id'=>$milestoneId,'project'=>$projectId]);return$s->rowCount()===1;}
    public function deleteMilestone(int$projectId,int$milestoneId):bool{$s=$this->connection()->prepare('DELETE FROM project_milestones WHERE id=:id AND project_id=:project');$s->execute(['id'=>$milestoneId,'project'=>$projectId]);return$s->rowCount()===1;}
    public function relationExists(string$table,int$id):bool{if(!in_array($table,['departments','research_units','media','staff'],true))return false;$extra=match($table){'departments','research_units','staff'=>' AND deleted_at IS NULL','media'=>' AND media_type="image" AND status="active" AND deleted_at IS NULL'};$s=$this->connection()->prepare("SELECT 1 FROM $table WHERE id=:id$extra LIMIT 1");$s->execute(['id'=>$id]);return$s->fetchColumn()!==false;}
    public function slugExists(string$slug,?int$exceptId=null):bool{$sql='SELECT 1 FROM projects WHERE slug=:slug AND deleted_at IS NULL';$params=['slug'=>$slug];if($exceptId!==null){$sql.=' AND id<>:id';$params['id']=$exceptId;}$s=$this->connection()->prepare($sql.' LIMIT 1');$s->execute($params);return$s->fetchColumn()!==false;}
    /** @param array<string,mixed> $data */ public function create(array$data):int{$fields=array_keys($data);$s=$this->connection()->prepare(sprintf('INSERT INTO projects (%s,publication_status) VALUES (%s,"draft")',implode(',',$fields),implode(',',array_map(fn($f)=>':'.$f,$fields))));$s->execute($data);return(int)$this->connection()->lastInsertId();}
    /** @param array<string,mixed> $data */ public function update(int$id,array$data):void{$sets=array_map(fn($f)=>$f.'=:'.$f,array_keys($data));$s=$this->connection()->prepare('UPDATE projects SET '.implode(',',$sets).' WHERE id=:id AND deleted_at IS NULL');$s->execute([...$data,'id'=>$id]);}
    public function replaceLeadUnit(int$projectId,?int$unitId):void{$this->connection()->prepare('DELETE FROM project_research_units WHERE project_id=:id')->execute(['id'=>$projectId]);if($unitId!==null)$this->connection()->prepare('INSERT INTO project_research_units(project_id,research_unit_id,is_lead_unit)VALUES(:project,:unit,1)')->execute(['project'=>$projectId,'unit'=>$unitId]);}
    public function changeStatus(int$id,string$status):void{$published=$status==='published'?',published_at=NOW()':($status==='draft'?',published_at=NULL':'');$s=$this->connection()->prepare('UPDATE projects SET publication_status=:status'.$published.' WHERE id=:id');$s->execute(['status'=>$status,'id'=>$id]);}
    public function addMember(int$projectId,?int$staffId,?string$externalName,?string$affiliation,?string$email,string$role,?string$title,?string$start,?string$end,int$order):int{if($staffId!==null)$this->connection()->prepare('DELETE FROM project_members WHERE project_id=:project AND staff_id=:staff')->execute(['project'=>$projectId,'staff'=>$staffId]);$s=$this->connection()->prepare('INSERT INTO project_members(project_id,staff_id,external_member_name,external_affiliation,external_email,project_role,role_title,start_date,end_date,display_order)VALUES(:project,:staff,:name,:affiliation,:email,:role,:title,:start,:end,:ordering)');$s->execute(['project'=>$projectId,'staff'=>$staffId,'name'=>$externalName,'affiliation'=>$affiliation,'email'=>$email,'role'=>$role,'title'=>$title,'start'=>$start,'end'=>$end,'ordering'=>$order]);return(int)$this->connection()->lastInsertId();}
    public function removeMember(int$projectId,int$memberId):bool{$s=$this->connection()->prepare('DELETE FROM project_members WHERE id=:id AND project_id=:project');$s->execute(['id'=>$memberId,'project'=>$projectId]);return$s->rowCount()===1;}
    public function recordRevision(int$id,?array$previous,array$revised,int$userId,string$note):void{$n=$this->connection()->prepare('SELECT COALESCE(MAX(revision_number),0)+1 FROM content_revisions WHERE entity_type="project" AND entity_id=:id');$n->execute(['id'=>$id]);$s=$this->connection()->prepare('INSERT INTO content_revisions(entity_type,entity_id,revision_number,previous_data,revised_data,revised_by,revision_note)VALUES("project",:id,:number,:previous,:revised,:user,:note)');$s->execute(['id'=>$id,'number'=>(int)$n->fetchColumn(),'previous'=>$previous===null?null:json_encode($previous,JSON_THROW_ON_ERROR),'revised'=>json_encode($revised,JSON_THROW_ON_ERROR),'user'=>$userId,'note'=>$note]);}
    public function recordApproval(int$id,string$action,int$userId,string$comment):void{$s=$this->connection()->prepare('INSERT INTO content_approvals(entity_type,entity_id,action,acted_by,comment)VALUES("project",:id,:action,:user,:comment)');$s->execute(['id'=>$id,'action'=>$action,'user'=>$userId,'comment'=>$comment!==''?$comment:null]);}
    /** @return list<array<string,mixed>> */ public function approvalHistory(int$id):array{$s=$this->connection()->prepare('SELECT ca.*,u.name AS actor_name FROM content_approvals ca LEFT JOIN users u ON u.id=ca.acted_by WHERE ca.entity_type="project" AND ca.entity_id=:id ORDER BY ca.created_at DESC,ca.id DESC');$s->execute(['id'=>$id]);return$s->fetchAll();}
    public function canAccess(int$userId,int$projectId):bool{if($this->scope->hasGlobalScope($userId))return true;$ids=$this->scope->departmentIds($userId);if($ids===[])return false;$s=$this->connection()->prepare('SELECT 1 FROM projects WHERE id=:id AND lead_department_id IN('.implode(',',array_map('intval',$ids)).') LIMIT 1');$s->execute(['id'=>$projectId]);return$s->fetchColumn()!==false;}
    public function canUseDepartment(int$userId,int$departmentId):bool{return$this->scope->hasGlobalScope($userId)||in_array($departmentId,$this->scope->departmentIds($userId),true);}
    public function canUseUnit(int$userId,?int$unitId):bool{if($unitId===null)return true;if($this->scope->hasGlobalScope($userId))return true;$ids=$this->scope->departmentIds($userId);if($ids===[])return false;$s=$this->connection()->prepare('SELECT 1 FROM research_units WHERE id=:id AND department_id IN('.implode(',',array_map('intval',$ids)).') AND deleted_at IS NULL LIMIT 1');$s->execute(['id'=>$unitId]);return$s->fetchColumn()!==false;}
    public function canUseStaff(int$userId,int$staffId):bool{if($this->scope->hasGlobalScope($userId))return true;$ids=$this->scope->departmentIds($userId);if($ids===[])return false;$s=$this->connection()->prepare('SELECT 1 FROM staff_departments WHERE staff_id=:staff AND department_id IN('.implode(',',array_map('intval',$ids)).') AND is_current=1 LIMIT 1');$s->execute(['staff'=>$staffId]);return$s->fetchColumn()!==false;}
    public function connection():PDO{return$this->database->connection();}
    private function scopeCondition(int$userId,string$alias):string{if($this->scope->hasGlobalScope($userId))return'1=1';$ids=$this->scope->departmentIds($userId);return$ids===[]?'1=0':($alias==='p'?$alias.'.lead_department_id':$alias.'.department_id').' IN('.implode(',',array_map('intval',$ids)).')';}
    /** @param list<int> $ids */ private function ids(string$field,array$ids):string{return$ids===[]?'1=0':$field.' IN('.implode(',',array_map('intval',$ids)).')';}
}
