<?php

declare(strict_types=1);

namespace FastWebsite\Repositories;

use FastWebsite\Core\Database;use FastWebsite\Services\DepartmentScopeService;use PDO;

final class PublicationRepository
{
    public function __construct(private readonly Database$database,private readonly DepartmentScopeService$scope){}
    /** @return list<array<string,mixed>> */ public function types():array{return$this->connection()->query('SELECT id,name,code FROM publication_types ORDER BY display_order,name')->fetchAll();}
    /** @return list<array<string,mixed>> */ public function availableStaff(int$userId):array{$ids=$this->scope->departmentIds($userId);$scope=$this->scope->hasGlobalScope($userId)?'1=1':($ids===[]?'1=0':'EXISTS(SELECT 1 FROM staff_departments sd WHERE sd.staff_id=s.id AND sd.department_id IN('.implode(',',array_map('intval',$ids)).') AND sd.is_current=1)');return$this->connection()->query('SELECT s.id,s.honorific_title,s.first_name,s.middle_name,s.last_name FROM staff s WHERE s.status="published" AND s.deleted_at IS NULL AND '.$scope.' ORDER BY s.first_name,s.last_name')->fetchAll();}
    // Staff self-service: an author's co-authors can legitimately be in any department, so this is unscoped (unlike availableStaff()).
    /** @return list<array<string,mixed>> */ public function allPublishedStaff():array{return$this->connection()->query('SELECT s.id,s.honorific_title,s.first_name,s.middle_name,s.last_name FROM staff s WHERE s.status="published" AND s.deleted_at IS NULL ORDER BY s.first_name,s.last_name')->fetchAll();}
    /** @return list<array<string,mixed>> */ public function projects(int$userId):array{$scope=$this->projectScope($userId,'p');return$this->connection()->query('SELECT p.id,p.title,p.short_title FROM projects p WHERE p.deleted_at IS NULL AND '.$scope.' ORDER BY p.title')->fetchAll();}
    /** @return list<array<string,mixed>> */ public function researchUnits(int$userId):array{$scope=$this->unitScope($userId,'ru');return$this->connection()->query('SELECT ru.id,ru.name,ru.acronym FROM research_units ru WHERE ru.deleted_at IS NULL AND '.$scope.' ORDER BY ru.name')->fetchAll();}
    /** @return array{items:list<array<string,mixed>>,total:int,page:int,pages:int} */ public function paginateAdmin(int$userId,string$search,string$status,string$type,int$page,int$perPage=15):array{$conditions=['pub.deleted_at IS NULL',$this->scopeCondition($userId,'pub')];$params=[];if($search!==''){$conditions[]='(pub.title LIKE :title OR pub.abstract LIKE :abstract OR pub.doi LIKE :doi OR pub.journal_name LIKE :journal)';$params=['title'=>'%'.$search.'%','abstract'=>'%'.$search.'%','doi'=>'%'.$search.'%','journal'=>'%'.$search.'%'];}if($status!==''){$conditions[]='pub.status=:status';$params['status']=$status;}if($type!==''){$conditions[]='pt.code=:type';$params['type']=$type;}$where=implode(' AND ',$conditions);$count=$this->connection()->prepare('SELECT COUNT(*) FROM publications pub INNER JOIN publication_types pt ON pt.id=pub.publication_type_id WHERE '.$where);$count->execute($params);$total=(int)$count->fetchColumn();$pages=max(1,(int)ceil($total/$perPage));$page=min(max(1,$page),$pages);$s=$this->connection()->prepare(sprintf('SELECT pub.id,pub.title,pub.slug,pub.publication_year,pub.journal_name,pub.status,pt.name AS type_name FROM publications pub INNER JOIN publication_types pt ON pt.id=pub.publication_type_id WHERE %s ORDER BY pub.publication_year DESC,pub.publication_date DESC,pub.title LIMIT %d OFFSET %d',$where,$perPage,($page-1)*$perPage));$s->execute($params);return['items'=>$s->fetchAll(),'total'=>$total,'page'=>$page,'pages'=>$pages];}
    /** @return array<string,mixed>|null */ public function findAdmin(int$id,int$userId):?array{$s=$this->connection()->prepare('SELECT pub.*,pt.name AS type_name FROM publications pub INNER JOIN publication_types pt ON pt.id=pub.publication_type_id WHERE pub.id=:id AND pub.deleted_at IS NULL AND '.$this->scopeCondition($userId,'pub').' LIMIT 1');$s->execute(['id'=>$id]);$r=$s->fetch();return is_array($r)?$r:null;}
    // Staff self-service: ownership-scoped via publication_authors, not RBAC/department scope.
    /** @return array<string,mixed>|null */ public function findOwn(int$id,int$staffId):?array{$s=$this->connection()->prepare('SELECT pub.*,pt.name AS type_name FROM publications pub INNER JOIN publication_types pt ON pt.id=pub.publication_type_id INNER JOIN publication_authors pa ON pa.publication_id=pub.id AND pa.staff_id=:staff WHERE pub.id=:id AND pub.deleted_at IS NULL LIMIT 1');$s->execute(['id'=>$id,'staff'=>$staffId]);$r=$s->fetch();return is_array($r)?$r:null;}
    /** @return list<array<string,mixed>> */ public function myPublications(int$staffId):array{$s=$this->connection()->prepare('SELECT DISTINCT pub.id,pub.title,pub.slug,pub.publication_year,pub.journal_name,pub.status,pt.name AS type_name FROM publications pub INNER JOIN publication_types pt ON pt.id=pub.publication_type_id INNER JOIN publication_authors pa ON pa.publication_id=pub.id AND pa.staff_id=:staff WHERE pub.deleted_at IS NULL ORDER BY pub.publication_year DESC,pub.publication_date DESC,pub.title');$s->execute(['staff'=>$staffId]);return$s->fetchAll();}
    /** @return array<string,mixed>|null */ public function findForUpdate(int$id):?array{$s=$this->connection()->prepare('SELECT * FROM publications WHERE id=:id AND deleted_at IS NULL FOR UPDATE');$s->execute(['id'=>$id]);$r=$s->fetch();return is_array($r)?$r:null;}
    /** @return array<string,mixed>|null */ public function findPublishedBySlug(string$slug):?array{$s=$this->connection()->prepare('SELECT pub.*,pt.name AS type_name FROM publications pub INNER JOIN publication_types pt ON pt.id=pub.publication_type_id WHERE pub.slug=:slug AND pub.status="published" AND pub.published_at IS NOT NULL AND pub.published_at<=NOW() AND pub.deleted_at IS NULL LIMIT 1');$s->execute(['slug'=>$slug]);$r=$s->fetch();return is_array($r)?$r:null;}
    /** @return array{items:list<array<string,mixed>>,total:int,page:int,pages:int} */ public function paginatePublished(string$search,string$type,string$access,string$year,int$page,int$perPage=15):array{$conditions=['pub.status="published"','pub.published_at IS NOT NULL','pub.published_at<=NOW()','pub.deleted_at IS NULL'];$params=[];if($search!==''){$conditions[]='(pub.title LIKE :title OR pub.abstract LIKE :abstract OR pub.doi LIKE :doi OR pub.journal_name LIKE :journal)';$params=['title'=>'%'.$search.'%','abstract'=>'%'.$search.'%','doi'=>'%'.$search.'%','journal'=>'%'.$search.'%'];}if($type!==''){$conditions[]='pt.code=:type';$params['type']=$type;}if($access!==''){$conditions[]='pub.access_type=:access';$params['access']=$access;}if($year!==''){$conditions[]='pub.publication_year=:year';$params['year']=(int)$year;}$where=implode(' AND ',$conditions);$count=$this->connection()->prepare('SELECT COUNT(*) FROM publications pub INNER JOIN publication_types pt ON pt.id=pub.publication_type_id WHERE '.$where);$count->execute($params);$total=(int)$count->fetchColumn();$pages=max(1,(int)ceil($total/$perPage));$page=min(max(1,$page),$pages);$s=$this->connection()->prepare(sprintf('SELECT pub.id,pub.title,pub.slug,pub.abstract,pub.journal_name,pub.publisher,pub.publication_year,pub.publication_date,pub.doi,pub.external_url,pub.access_type,pt.name AS type_name FROM publications pub INNER JOIN publication_types pt ON pt.id=pub.publication_type_id WHERE %s ORDER BY pub.publication_year DESC,pub.publication_date DESC,pub.title LIMIT %d OFFSET %d',$where,$perPage,($page-1)*$perPage));$s->execute($params);return['items'=>$s->fetchAll(),'total'=>$total,'page'=>$page,'pages'=>$pages];}
    /** @return list<array<string,mixed>> */ public function authors(int$publicationId,bool$publishedOnly=false):array{$extra=$publishedOnly?' AND (pa.staff_id IS NULL OR (s.status="published" AND s.published_at IS NOT NULL AND s.published_at<=NOW()))':'';$s=$this->connection()->prepare('SELECT pa.*,s.honorific_title,s.first_name,s.middle_name,s.last_name,s.slug AS staff_slug FROM publication_authors pa LEFT JOIN staff s ON s.id=pa.staff_id AND s.deleted_at IS NULL WHERE pa.publication_id=:id'.$extra.' ORDER BY pa.author_order,pa.id');$s->execute(['id'=>$publicationId]);return$s->fetchAll();}
    /** @return list<array<string,mixed>> */ public function linkedProjects(int$id,bool$publishedOnly=false):array{$extra=$publishedOnly?' AND p.publication_status="published" AND p.published_at IS NOT NULL AND p.published_at<=NOW()':'';$s=$this->connection()->prepare('SELECT p.id,p.title,p.short_title,p.slug FROM publication_projects pp INNER JOIN projects p ON p.id=pp.project_id AND p.deleted_at IS NULL'.$extra.' WHERE pp.publication_id=:id ORDER BY p.title');$s->execute(['id'=>$id]);return$s->fetchAll();}
    /** @return list<array<string,mixed>> */ public function linkedUnits(int$id,bool$publishedOnly=false):array{$extra=$publishedOnly?' AND ru.status="published" AND ru.published_at IS NOT NULL AND ru.published_at<=NOW()':'';$s=$this->connection()->prepare('SELECT ru.id,ru.name,ru.acronym,ru.slug FROM publication_research_units pru INNER JOIN research_units ru ON ru.id=pru.research_unit_id AND ru.deleted_at IS NULL'.$extra.' WHERE pru.publication_id=:id ORDER BY ru.name');$s->execute(['id'=>$id]);return$s->fetchAll();}
    /** @return list<array<string,mixed>> */ public function staffPublications(int$staffId,int$limit=20):array{$s=$this->connection()->prepare(sprintf('SELECT pub.title,pub.slug,pub.publication_year,pub.journal_name,pub.doi,pt.name AS type_name,pa.author_order FROM publication_authors pa INNER JOIN publications pub ON pub.id=pa.publication_id AND pub.status="published" AND pub.published_at IS NOT NULL AND pub.published_at<=NOW() AND pub.deleted_at IS NULL INNER JOIN publication_types pt ON pt.id=pub.publication_type_id WHERE pa.staff_id=:staff ORDER BY pub.publication_year DESC,pub.publication_date DESC,pub.title LIMIT %d',$limit));$s->execute(['staff'=>$staffId]);return$s->fetchAll();}
    public function relationExists(string$table,int$id):bool{if(!in_array($table,['publication_types','staff','projects','research_units'],true))return false;$extra=match($table){'staff','projects','research_units'=>' AND deleted_at IS NULL',default=>''};$s=$this->connection()->prepare("SELECT 1 FROM $table WHERE id=:id$extra LIMIT 1");$s->execute(['id'=>$id]);return$s->fetchColumn()!==false;}
    public function slugExists(string$slug,?int$exceptId=null):bool{return$this->uniqueExists('slug',$slug,$exceptId);}public function doiExists(string$doi,?int$exceptId=null):bool{return$this->uniqueExists('doi',$doi,$exceptId);}
    /** @param array<string,mixed> $data */ public function create(array$data):int{$fields=array_keys($data);$s=$this->connection()->prepare(sprintf('INSERT INTO publications(%s,status)VALUES(%s,"draft")',implode(',',$fields),implode(',',array_map(fn($f)=>':'.$f,$fields))));$s->execute($data);return(int)$this->connection()->lastInsertId();}
    /** @param array<string,mixed> $data */ public function update(int$id,array$data):void{$sets=array_map(fn($f)=>$f.'=:'.$f,array_keys($data));$s=$this->connection()->prepare('UPDATE publications SET '.implode(',',$sets).' WHERE id=:id AND deleted_at IS NULL');$s->execute([...$data,'id'=>$id]);}
    public function replaceLinks(int$id,?int$projectId,?int$unitId):void{$this->connection()->prepare('DELETE FROM publication_projects WHERE publication_id=:id')->execute(['id'=>$id]);$this->connection()->prepare('DELETE FROM publication_research_units WHERE publication_id=:id')->execute(['id'=>$id]);if($projectId!==null)$this->connection()->prepare('INSERT INTO publication_projects(publication_id,project_id)VALUES(:publication,:project)')->execute(['publication'=>$id,'project'=>$projectId]);if($unitId!==null)$this->connection()->prepare('INSERT INTO publication_research_units(publication_id,research_unit_id)VALUES(:publication,:unit)')->execute(['publication'=>$id,'unit'=>$unitId]);}
    public function changeStatus(int$id,string$status):void{$published=$status==='published'?',published_at=NOW()':($status==='draft'?',published_at=NULL':'');$s=$this->connection()->prepare('UPDATE publications SET status=:status'.$published.' WHERE id=:id');$s->execute(['status'=>$status,'id'=>$id]);}
    public function addAuthor(int$id,?int$staffId,?string$name,?string$affiliation,?string$orcid,int$order,bool$corresponding):int{$this->connection()->prepare('UPDATE publication_authors SET author_order=author_order+1 WHERE publication_id=:id AND author_order>=:ordering ORDER BY author_order DESC')->execute(['id'=>$id,'ordering'=>$order]);if($staffId!==null)$this->connection()->prepare('DELETE FROM publication_authors WHERE publication_id=:id AND staff_id=:staff')->execute(['id'=>$id,'staff'=>$staffId]);$s=$this->connection()->prepare('INSERT INTO publication_authors(publication_id,staff_id,external_author_name,external_affiliation,external_orcid,author_order,is_corresponding)VALUES(:publication,:staff,:name,:affiliation,:orcid,:ordering,:corresponding)');$s->execute(['publication'=>$id,'staff'=>$staffId,'name'=>$name,'affiliation'=>$affiliation,'orcid'=>$orcid,'ordering'=>$order,'corresponding'=>$corresponding?1:0]);return(int)$this->connection()->lastInsertId();}
    public function removeAuthor(int$id,int$authorId):bool{$s=$this->connection()->prepare('DELETE FROM publication_authors WHERE id=:author AND publication_id=:publication');$s->execute(['author'=>$authorId,'publication'=>$id]);return$s->rowCount()===1;}
    public function recordRevision(int$id,?array$previous,array$revised,int$userId,string$note):void{$n=$this->connection()->prepare('SELECT COALESCE(MAX(revision_number),0)+1 FROM content_revisions WHERE entity_type="publication" AND entity_id=:id');$n->execute(['id'=>$id]);$s=$this->connection()->prepare('INSERT INTO content_revisions(entity_type,entity_id,revision_number,previous_data,revised_data,revised_by,revision_note)VALUES("publication",:id,:number,:previous,:revised,:user,:note)');$s->execute(['id'=>$id,'number'=>(int)$n->fetchColumn(),'previous'=>$previous===null?null:json_encode($previous,JSON_THROW_ON_ERROR),'revised'=>json_encode($revised,JSON_THROW_ON_ERROR),'user'=>$userId,'note'=>$note]);}
    public function recordApproval(int$id,string$action,int$userId,string$comment):void{$s=$this->connection()->prepare('INSERT INTO content_approvals(entity_type,entity_id,action,acted_by,comment)VALUES("publication",:id,:action,:user,:comment)');$s->execute(['id'=>$id,'action'=>$action,'user'=>$userId,'comment'=>$comment!==''?$comment:null]);}
    /** @return list<array<string,mixed>> */ public function approvalHistory(int$id):array{$s=$this->connection()->prepare('SELECT ca.*,u.name AS actor_name FROM content_approvals ca LEFT JOIN users u ON u.id=ca.acted_by WHERE ca.entity_type="publication" AND ca.entity_id=:id ORDER BY ca.created_at DESC,ca.id DESC');$s->execute(['id'=>$id]);return$s->fetchAll();}
    public function canAccess(int$userId,int$id):bool{if($this->scope->hasGlobalScope($userId))return true;$ids=$this->scope->departmentIds($userId);if($ids===[])return false;$list=implode(',',array_map('intval',$ids));$s=$this->connection()->prepare('SELECT 1 FROM publications pub WHERE pub.id=:id AND (EXISTS(SELECT 1 FROM publication_authors pa INNER JOIN staff_departments sd ON sd.staff_id=pa.staff_id AND sd.is_current=1 WHERE pa.publication_id=pub.id AND sd.department_id IN('.$list.')) OR EXISTS(SELECT 1 FROM publication_projects pp INNER JOIN projects p ON p.id=pp.project_id WHERE pp.publication_id=pub.id AND p.lead_department_id IN('.$list.')) OR EXISTS(SELECT 1 FROM publication_research_units pru INNER JOIN research_units ru ON ru.id=pru.research_unit_id WHERE pru.publication_id=pub.id AND ru.department_id IN('.$list.'))) LIMIT 1');$s->execute(['id'=>$id]);return$s->fetchColumn()!==false;}
    public function canUseStaff(int$userId,int$staffId):bool{if($this->scope->hasGlobalScope($userId))return true;$ids=$this->scope->departmentIds($userId);if($ids===[])return false;$s=$this->connection()->prepare('SELECT 1 FROM staff_departments WHERE staff_id=:staff AND department_id IN('.implode(',',array_map('intval',$ids)).') AND is_current=1 LIMIT 1');$s->execute(['staff'=>$staffId]);return$s->fetchColumn()!==false;}
    public function canUseProject(int$userId,?int$id):bool{if($id===null)return true;if($this->scope->hasGlobalScope($userId))return true;$ids=$this->scope->departmentIds($userId);if($ids===[])return false;$s=$this->connection()->prepare('SELECT 1 FROM projects WHERE id=:id AND lead_department_id IN('.implode(',',array_map('intval',$ids)).') AND deleted_at IS NULL LIMIT 1');$s->execute(['id'=>$id]);return$s->fetchColumn()!==false;}public function canUseUnit(int$userId,?int$id):bool{if($id===null)return true;if($this->scope->hasGlobalScope($userId))return true;$ids=$this->scope->departmentIds($userId);if($ids===[])return false;$s=$this->connection()->prepare('SELECT 1 FROM research_units WHERE id=:id AND department_id IN('.implode(',',array_map('intval',$ids)).') AND deleted_at IS NULL LIMIT 1');$s->execute(['id'=>$id]);return$s->fetchColumn()!==false;}public function hasGlobalScope(int$userId):bool{return$this->scope->hasGlobalScope($userId);}
    public function connection():PDO{return$this->database->connection();}
    private function uniqueExists(string$field,string$value,?int$exceptId):bool{$sql='SELECT 1 FROM publications WHERE '.$field.'=:value AND deleted_at IS NULL';$params=['value'=>$value];if($exceptId!==null){$sql.=' AND id<>:id';$params['id']=$exceptId;}$s=$this->connection()->prepare($sql.' LIMIT 1');$s->execute($params);return$s->fetchColumn()!==false;}
    private function scopeCondition(int$userId,string$alias):string{if($this->scope->hasGlobalScope($userId))return'1=1';$ids=$this->scope->departmentIds($userId);if($ids===[])return'1=0';$list=implode(',',array_map('intval',$ids));return'(EXISTS(SELECT 1 FROM publication_authors scoped_pa INNER JOIN staff_departments scoped_sd ON scoped_sd.staff_id=scoped_pa.staff_id AND scoped_sd.is_current=1 WHERE scoped_pa.publication_id='.$alias.'.id AND scoped_sd.department_id IN('.$list.')) OR EXISTS(SELECT 1 FROM publication_projects scoped_pp INNER JOIN projects scoped_p ON scoped_p.id=scoped_pp.project_id WHERE scoped_pp.publication_id='.$alias.'.id AND scoped_p.lead_department_id IN('.$list.')) OR EXISTS(SELECT 1 FROM publication_research_units scoped_pru INNER JOIN research_units scoped_ru ON scoped_ru.id=scoped_pru.research_unit_id WHERE scoped_pru.publication_id='.$alias.'.id AND scoped_ru.department_id IN('.$list.')))';}
    private function projectScope(int$userId,string$alias):string{if($this->scope->hasGlobalScope($userId))return'1=1';$ids=$this->scope->departmentIds($userId);return$ids===[]?'1=0':$alias.'.lead_department_id IN('.implode(',',array_map('intval',$ids)).')';}private function unitScope(int$userId,string$alias):string{if($this->scope->hasGlobalScope($userId))return'1=1';$ids=$this->scope->departmentIds($userId);return$ids===[]?'1=0':$alias.'.department_id IN('.implode(',',array_map('intval',$ids)).')';}
}
